// frontend-react/src/pages/Users.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import { userApi } from '@/api';
import type { AuditLog, Org, UserRecord } from '@/api';
import Badge from '@/components/ui/badge';
import Button from '@/components/ui/button';
import Dialog from '@/components/ui/dialog';
import { Table } from '@/components/ui/table';
import { useToast } from '@/components/ui/use-toast';
import { useUserStore } from '@/stores/user';

const PAGE_SIZE = 10;

const fieldCls =
  'rounded-md border border-cyan-500/20 bg-[#1a2340] px-3 py-2 text-sm text-gray-300 outline-none transition-colors placeholder:text-gray-500 focus:border-cyan-500/60';

type TabKey = 'users' | 'audit';

/** 角色选项（与后端 roles 表保持一致：1=admin 2=auditor 3=viewer） */
const ROLE_OPTIONS = [
  { value: 1, label: '管理员' },
  { value: 2, label: '审计员' },
  { value: 3, label: '普通用户' }
];

const OPERATION_TYPES = [
  { value: 'login', label: '登录' },
  { value: 'scan', label: '扫描' },
  { value: 'baseline_check', label: '基线检查' },
  { value: 'virus_scan', label: '病毒检测' },
  { value: 'policy', label: '策略操作' },
  { value: 'config', label: '配置变更' },
  { value: 'password_change', label: '密码修改' }
];

function formatTime(t?: string): string {
  return t ? new Date(t).toLocaleString('zh-CN') : '-';
}

/** 角色展示（优先 role_name，回退 role_id） */
function roleTag(roleName?: string, roleId?: number) {
  if (roleName === 'admin' || roleId === 1) return { label: '管理员', variant: 'danger' as const };
  if (roleName === 'auditor' || roleId === 2) return { label: '审计员', variant: 'warning' as const };
  if (roleName === 'viewer' || roleId === 3) return { label: '普通用户', variant: 'default' as const };
  return { label: roleName || (roleId !== undefined ? `角色${roleId}` : '-'), variant: 'default' as const };
}

function resultTag(result?: string) {
  return result === 'success'
    ? { label: '成功', variant: 'success' as const }
    : { label: '失败', variant: 'danger' as const };
}

function Pagination({
  page,
  total,
  pageSize,
  onChange
}: {
  page: number;
  total: number;
  pageSize: number;
  onChange: (p: number) => void;
}) {
  const pages = Math.max(1, Math.ceil(total / pageSize));
  if (pages <= 1) return null;
  return (
    <div className="mt-4 flex items-center justify-end gap-2 text-xs text-gray-400">
      <span>共 {total} 条</span>
      <button
        type="button"
        disabled={page <= 1}
        onClick={() => onChange(page - 1)}
        className="rounded border border-white/10 px-2 py-1 transition-colors hover:border-cyan-500/40 disabled:opacity-40"
      >
        上一页
      </button>
      <span className="px-1">
        {page} / {pages}
      </span>
      <button
        type="button"
        disabled={page >= pages}
        onClick={() => onChange(page + 1)}
        className="rounded border border-white/10 px-2 py-1 transition-colors hover:border-cyan-500/40 disabled:opacity-40"
      >
        下一页
      </button>
    </div>
  );
}

interface UserForm {
  username: string;
  password: string;
  role_id: number;
  department: string;
  org_id: number;
}

const EMPTY_USER_FORM: UserForm = { username: '', password: '', role_id: 3, department: '', org_id: 1 };

interface EditForm {
  id: number;
  username: string;
  role_id: number;
  department: string;
  org_id: number;
  status: number;
}

export default function Users() {
  const { toast } = useToast();
  const currentUser = useUserStore((s) => s.user);
  const [activeTab, setActiveTab] = useState<TabKey>('users');
  const [loading, setLoading] = useState(true);

  // 用户列表
  const [users, setUsers] = useState<UserRecord[]>([]);
  const [orgs, setOrgs] = useState<Org[]>([]);
  const [page, setPage] = useState(1);

  // 新建
  const [addOpen, setAddOpen] = useState(false);
  const [addForm, setAddForm] = useState<UserForm>(EMPTY_USER_FORM);
  const [addSaving, setAddSaving] = useState(false);

  // 编辑
  const [editOpen, setEditOpen] = useState(false);
  const [editForm, setEditForm] = useState<EditForm | null>(null);
  const [editSaving, setEditSaving] = useState(false);

  // 删除确认
  const [deleteTarget, setDeleteTarget] = useState<UserRecord | null>(null);
  const [deleting, setDeleting] = useState(false);

  // 审计日志
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([]);
  const [auditPage, setAuditPage] = useState(1);
  const [auditFilter, setAuditFilter] = useState({ username: '', operation_type: '', start_date: '', end_date: '' });

  const orgName = useCallback(
    (orgId?: number) => {
      if (orgId === undefined || orgId === null) return '-';
      return orgs.find((o) => o.id === orgId)?.name || `组织#${orgId}`;
    },
    [orgs]
  );

  const loadUsers = useCallback(async () => {
    setLoading(true);
    try {
      const [uData, oData] = await Promise.all([userApi.list({ page: 1, pageSize: 100 }), userApi.orgs()]);
      setUsers(uData?.list || []);
      setOrgs(oData || []);
    } catch {
      setUsers([]);
      setOrgs([]);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    loadUsers();
  }, [loadUsers]);

  const paginatedUsers = useMemo(() => {
    const s = (page - 1) * PAGE_SIZE;
    return users.slice(s, s + PAGE_SIZE);
  }, [users, page]);

  async function loadAudit() {
    setLoading(true);
    try {
      const logs = await userApi.auditLogs({
        page: 1,
        pageSize: 100,
        username: auditFilter.username.trim() || undefined,
        operation_type: auditFilter.operation_type || undefined,
        start_date: auditFilter.start_date || undefined,
        end_date: auditFilter.end_date || undefined
      });
      setAuditLogs(logs || []);
      setAuditPage(1);
    } catch {
      setAuditLogs([]);
    }
    setLoading(false);
  }

  function switchTab(tab: TabKey) {
    setActiveTab(tab);
    if (tab === 'audit') loadAudit();
  }

  function resetAuditFilter() {
    setAuditFilter({ username: '', operation_type: '', start_date: '', end_date: '' });
    loadAudit();
  }

  function openAdd() {
    setAddForm({ ...EMPTY_USER_FORM, org_id: orgs[0]?.id || 1 });
    setAddOpen(true);
  }

  async function submitAdd() {
    if (!addForm.username.trim()) {
      toast({ title: '请输入用户名', variant: 'warning' });
      return;
    }
    if (!addForm.password) {
      toast({ title: '请输入密码', variant: 'warning' });
      return;
    }
    if (addForm.password.length < 8) {
      toast({ title: '密码长度不能少于8位', variant: 'warning' });
      return;
    }
    setAddSaving(true);
    try {
      await userApi.create({
        username: addForm.username.trim(),
        password: addForm.password,
        role_id: addForm.role_id,
        department: addForm.department.trim(),
        org_id: addForm.org_id
      });
      toast({ title: '用户创建成功', variant: 'success' });
      setAddOpen(false);
      loadUsers();
    } catch {
      // http 拦截器已提示
    }
    setAddSaving(false);
  }

  function openEdit(u: UserRecord) {
    setEditForm({
      id: u.id,
      username: u.username,
      role_id: u.role_id,
      department: u.department || '',
      org_id: u.org_id || 1,
      status: u.status || 1
    });
    setEditOpen(true);
  }

  async function submitEdit() {
    if (!editForm) return;
    setEditSaving(true);
    try {
      await userApi.update(editForm.id, {
        role_id: editForm.role_id,
        department: editForm.department.trim(),
        status: editForm.status
      });
      toast({ title: '用户信息已更新', variant: 'success' });
      setEditOpen(false);
      loadUsers();
    } catch {
      // http 拦截器已提示
    }
    setEditSaving(false);
  }

  async function toggleUserStatus(u: UserRecord) {
    const next = u.status ? 0 : 1;
    try {
      await userApi.update(u.id, { status: next });
      toast({ title: `用户已${next ? '启用' : '禁用'}`, variant: 'success' });
      loadUsers();
    } catch {
      // http 拦截器已提示
    }
  }

  async function confirmDelete() {
    if (!deleteTarget) return;
    setDeleting(true);
    try {
      await userApi.remove(deleteTarget.id);
      toast({ title: '用户已删除', variant: 'success' });
      setDeleteTarget(null);
      loadUsers();
    } catch {
      // http 拦截器已提示
    }
    setDeleting(false);
  }

  function exportAuditLogs() {
    if (auditLogs.length === 0) {
      toast({ title: '暂无可导出的审计日志', variant: 'warning' });
      return;
    }
    const headers = '用户,操作类型,操作目标,IP,结果,时间\n';
    const rows = auditLogs
      .map(
        (l) =>
          `${l.username || '-'},${l.operation_type || '-'},${l.operation_target || '-'},${l.client_ip || '-'},${
            l.result || 'success'
          },${formatTime(l.created_at)}`
      )
      .join('\n');
    const blob = new Blob(['\uFEFF' + headers + rows], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'audit_logs.csv';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: '审计日志已导出', variant: 'success' });
  }

  const tabs: Array<[TabKey, string]> = [
    ['users', '用户列表'],
    ['audit', '审计日志']
  ];

  return (
    <div className="space-y-5">
      {/* 页头 */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-white">用户管理</h2>
          <p className="mt-1 text-sm text-gray-400">系统用户管理与操作审计</p>
        </div>
        {activeTab === 'users' && (
          <Button size="sm" onClick={openAdd}>
            添加用户
          </Button>
        )}
      </div>

      <div className="rounded-lg border border-cyan-500/20 bg-[#16213e]/80 p-5">
        {/* Tabs */}
        <div className="mb-4 flex gap-6 border-b border-white/10">
          {tabs.map(([key, label]) => (
            <button
              key={key}
              type="button"
              onClick={() => switchTab(key)}
              className={`border-b-2 pb-2 text-sm transition-colors ${
                activeTab === key
                  ? 'border-cyan-400 text-cyan-300'
                  : 'border-transparent text-gray-400 hover:text-gray-200'
              }`}
            >
              {label}
            </button>
          ))}
        </div>

        {/* 用户列表 */}
        {activeTab === 'users' && (
          <>
            <Table>
              <thead>
                <tr className="border-b border-cyan-500/20 text-left text-xs text-cyan-200/70">
                  <th className="px-2 py-2 font-medium">ID</th>
                  <th className="px-2 py-2 font-medium">用户名</th>
                  <th className="px-2 py-2 font-medium">角色</th>
                  <th className="px-2 py-2 font-medium">部门</th>
                  <th className="px-2 py-2 font-medium">组织</th>
                  <th className="px-2 py-2 font-medium">状态</th>
                  <th className="px-2 py-2 font-medium">创建时间</th>
                  <th className="px-2 py-2 font-medium">操作</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {paginatedUsers.map((u) => {
                  const role = roleTag(u.role_name, u.role_id);
                  const active = !!u.status;
                  return (
                    <tr key={u.id} className="hover:bg-white/5">
                      <td className="px-2 py-2 font-mono text-xs text-gray-400">{u.id}</td>
                      <td className="px-2 py-2 text-gray-300">{u.username}</td>
                      <td className="px-2 py-2">
                        <Badge variant={role.variant}>{role.label}</Badge>
                      </td>
                      <td className="px-2 py-2 text-gray-400">{u.department || '-'}</td>
                      <td className="px-2 py-2 text-gray-400">{orgName(u.org_id)}</td>
                      <td className="px-2 py-2">
                        <Badge variant={active ? 'success' : 'default'}>{active ? '正常' : '禁用'}</Badge>
                      </td>
                      <td className="px-2 py-2 text-gray-400">{formatTime(u.created_at)}</td>
                      <td className="px-2 py-2">
                        <div className="flex gap-3">
                          <button
                            type="button"
                            onClick={() => openEdit(u)}
                            className="text-xs text-cyan-400 transition-colors hover:text-cyan-300"
                          >
                            编辑
                          </button>
                          <button
                            type="button"
                            onClick={() => toggleUserStatus(u)}
                            className="text-xs text-amber-400 transition-colors hover:text-amber-300"
                          >
                            {active ? '禁用' : '启用'}
                          </button>
                          {currentUser?.id !== u.id && (
                            <button
                              type="button"
                              onClick={() => setDeleteTarget(u)}
                              className="text-xs text-red-400 transition-colors hover:text-red-300"
                            >
                              删除
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })}
                {paginatedUsers.length === 0 && (
                  <tr>
                    <td colSpan={8} className="px-2 py-6 text-center text-gray-500">
                      {loading ? '加载中…' : '暂无用户'}
                    </td>
                  </tr>
                )}
              </tbody>
            </Table>
            <Pagination page={page} total={users.length} pageSize={PAGE_SIZE} onChange={setPage} />
          </>
        )}

        {/* 审计日志 */}
        {activeTab === 'audit' && (
          <>
            <div className="mb-4 flex flex-wrap items-end gap-3">
              <div>
                <label className="mb-1 block text-xs text-gray-500">用户名</label>
                <input
                  className={`${fieldCls} w-[150px]`}
                  value={auditFilter.username}
                  placeholder="用户名"
                  onChange={(e) => setAuditFilter({ ...auditFilter, username: e.target.value })}
                />
              </div>
              <div>
                <label className="mb-1 block text-xs text-gray-500">操作类型</label>
                <select
                  className={`${fieldCls} w-[150px]`}
                  value={auditFilter.operation_type}
                  onChange={(e) => setAuditFilter({ ...auditFilter, operation_type: e.target.value })}
                >
                  <option value="">全部</option>
                  {OPERATION_TYPES.map((opt) => (
                    <option key={opt.value} value={opt.value}>
                      {opt.label}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="mb-1 block text-xs text-gray-500">开始日期</label>
                <input
                  type="date"
                  className={`${fieldCls} w-[150px]`}
                  value={auditFilter.start_date}
                  onChange={(e) => setAuditFilter({ ...auditFilter, start_date: e.target.value })}
                />
              </div>
              <div>
                <label className="mb-1 block text-xs text-gray-500">结束日期</label>
                <input
                  type="date"
                  className={`${fieldCls} w-[150px]`}
                  value={auditFilter.end_date}
                  onChange={(e) => setAuditFilter({ ...auditFilter, end_date: e.target.value })}
                />
              </div>
              <div className="flex gap-2">
                <Button size="sm" onClick={loadAudit}>
                  查询
                </Button>
                <Button size="sm" variant="outline" onClick={resetAuditFilter}>
                  重置
                </Button>
                <Button size="sm" variant="outline" onClick={exportAuditLogs}>
                  导出CSV
                </Button>
              </div>
            </div>
            <Table>
              <thead>
                <tr className="border-b border-cyan-500/20 text-left text-xs text-cyan-200/70">
                  <th className="px-2 py-2 font-medium">日志ID</th>
                  <th className="px-2 py-2 font-medium">操作用户</th>
                  <th className="px-2 py-2 font-medium">操作类型</th>
                  <th className="px-2 py-2 font-medium">操作对象</th>
                  <th className="px-2 py-2 font-medium">来源IP</th>
                  <th className="px-2 py-2 font-medium">结果</th>
                  <th className="px-2 py-2 font-medium">时间</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {auditLogs.slice((auditPage - 1) * PAGE_SIZE, auditPage * PAGE_SIZE).map((l) => (
                  <tr key={l.id} className="hover:bg-white/5">
                    <td className="px-2 py-2 font-mono text-xs text-gray-400">AUD-{l.id}</td>
                    <td className="px-2 py-2 text-gray-300">{l.username || '-'}</td>
                    <td className="px-2 py-2 text-gray-400">{l.operation_type || '-'}</td>
                    <td className="max-w-[200px] truncate px-2 py-2 text-gray-400" title={l.operation_target || ''}>
                      {l.operation_target || '-'}
                    </td>
                    <td className="px-2 py-2 text-gray-400">{l.client_ip || '-'}</td>
                    <td className="px-2 py-2">
                      <Badge variant={resultTag(l.result).variant}>{resultTag(l.result).label}</Badge>
                    </td>
                    <td className="px-2 py-2 text-gray-400">{formatTime(l.created_at)}</td>
                  </tr>
                ))}
                {auditLogs.length === 0 && (
                  <tr>
                    <td colSpan={7} className="px-2 py-6 text-center text-gray-500">
                      {loading ? '加载中…' : '暂无审计日志'}
                    </td>
                  </tr>
                )}
              </tbody>
            </Table>
            <Pagination page={auditPage} total={auditLogs.length} pageSize={PAGE_SIZE} onChange={setAuditPage} />
          </>
        )}
      </div>

      {/* 新建用户 */}
      <Dialog
        open={addOpen}
        onOpenChange={(open) => !open && setAddOpen(false)}
        title="添加用户"
        footer={
          <>
            <Button size="sm" variant="outline" onClick={() => setAddOpen(false)}>
              取消
            </Button>
            <Button size="sm" disabled={addSaving} onClick={submitAdd}>
              {addSaving ? '添加中…' : '添加'}
            </Button>
          </>
        }
      >
        <div className="space-y-4">
          <div>
            <label className="mb-1 block text-xs text-gray-400">用户名（必填）</label>
            <input
              className={`${fieldCls} w-full`}
              value={addForm.username}
              placeholder="请输入用户名"
              onChange={(e) => setAddForm({ ...addForm, username: e.target.value })}
            />
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-400">密码（必填，≥8位且含字母和数字）</label>
            <input
              className={`${fieldCls} w-full`}
              type="password"
              value={addForm.password}
              placeholder="请输入密码"
              onChange={(e) => setAddForm({ ...addForm, password: e.target.value })}
            />
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-400">角色</label>
            <select
              className={`${fieldCls} w-full`}
              value={addForm.role_id}
              onChange={(e) => setAddForm({ ...addForm, role_id: Number(e.target.value) })}
            >
              {ROLE_OPTIONS.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-400">部门</label>
            <input
              className={`${fieldCls} w-full`}
              value={addForm.department}
              placeholder="请输入部门"
              onChange={(e) => setAddForm({ ...addForm, department: e.target.value })}
            />
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-400">组织</label>
            <select
              className={`${fieldCls} w-full`}
              value={addForm.org_id}
              onChange={(e) => setAddForm({ ...addForm, org_id: Number(e.target.value) })}
            >
              {orgs.map((o) => (
                <option key={o.id} value={o.id}>
                  {o.name}
                </option>
              ))}
              {orgs.length === 0 && <option value={1}>组织#1</option>}
            </select>
          </div>
        </div>
      </Dialog>

      {/* 编辑用户 */}
      <Dialog
        open={editOpen}
        onOpenChange={(open) => !open && setEditOpen(false)}
        title="编辑用户"
        footer={
          <>
            <Button size="sm" variant="outline" onClick={() => setEditOpen(false)}>
              取消
            </Button>
            <Button size="sm" disabled={editSaving} onClick={submitEdit}>
              {editSaving ? '保存中…' : '保存'}
            </Button>
          </>
        }
      >
        {editForm && (
          <div className="space-y-4">
            <div>
              <label className="mb-1 block text-xs text-gray-400">用户名</label>
              <input className={`${fieldCls} w-full`} value={editForm.username} disabled />
            </div>
            <div>
              <label className="mb-1 block text-xs text-gray-400">角色</label>
              <select
                className={`${fieldCls} w-full`}
                value={editForm.role_id}
                onChange={(e) => setEditForm({ ...editForm, role_id: Number(e.target.value) })}
              >
                {ROLE_OPTIONS.map((opt) => (
                  <option key={opt.value} value={opt.value}>
                    {opt.label}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="mb-1 block text-xs text-gray-400">部门</label>
              <input
                className={`${fieldCls} w-full`}
                value={editForm.department}
                placeholder="请输入部门"
                onChange={(e) => setEditForm({ ...editForm, department: e.target.value })}
              />
            </div>
            <div>
              <label className="mb-1 block text-xs text-gray-400">组织</label>
              <select
                className={`${fieldCls} w-full`}
                value={editForm.org_id}
                onChange={(e) => setEditForm({ ...editForm, org_id: Number(e.target.value) })}
              >
                {orgs.map((o) => (
                  <option key={o.id} value={o.id}>
                    {o.name}
                  </option>
                ))}
                {orgs.length === 0 && <option value={1}>组织#1</option>}
              </select>
            </div>
            <div>
              <label className="mb-1 block text-xs text-gray-400">状态</label>
              <select
                className={`${fieldCls} w-full`}
                value={editForm.status}
                onChange={(e) => setEditForm({ ...editForm, status: Number(e.target.value) })}
              >
                <option value={1}>正常</option>
                <option value={0}>禁用</option>
              </select>
            </div>
          </div>
        )}
      </Dialog>

      {/* 删除确认 */}
      <Dialog
        open={deleteTarget !== null}
        onOpenChange={(open) => !open && setDeleteTarget(null)}
        title="删除用户"
        footer={
          <>
            <Button size="sm" variant="outline" onClick={() => setDeleteTarget(null)}>
              取消
            </Button>
            <Button size="sm" variant="destructive" disabled={deleting} onClick={confirmDelete}>
              {deleting ? '删除中…' : '确认删除'}
            </Button>
          </>
        }
      >
        <p className="text-sm text-gray-700">
          确定要删除用户 <span className="font-semibold text-gray-900">{deleteTarget?.username}</span> 吗？此操作不可恢复。
        </p>
      </Dialog>
    </div>
  );
}

// frontend-app/src/views/Users.vue
<template>
  <div v-loading="loading">
    <div class="page-header">
      <div>
        <div class="page-title">用户管理</div>
        <div class="page-desc">系统用户管理与操作审计</div>
      </div>
      <el-button type="primary" size="small" @click="openAdd"
        ><el-icon><Plus /></el-icon> 添加用户</el-button
      >
    </div>
    <div class="chart-card">
      <el-tabs v-model="activeTab">
        <el-tab-pane label="用户列表" name="users">
          <el-table :data="paginatedUsers" size="small" style="width: 100%">
            <el-table-column prop="id" label="ID" width="60" />
            <el-table-column prop="username" label="用户名" width="120" />
            <el-table-column prop="role" label="角色" width="90">
              <template #default="{ row }"
                ><el-tag :type="getRoleTag(row.role).type" size="small">{{
                  getRoleTag(row.role).label
                }}</el-tag></template
              >
            </el-table-column>
            <el-table-column prop="department" label="部门" width="130" />
            <el-table-column prop="status" label="状态" width="80">
              <template #default="{ row }"
                ><el-tag :type="row.status === 'active' ? 'success' : 'danger'" size="small">{{
                  row.status === 'active' ? '正常' : '禁用'
                }}</el-tag></template
              >
            </el-table-column>
            <el-table-column prop="createTime" label="创建时间" width="160" />
            <el-table-column prop="lastLogin" label="最后登录" width="160" />
            <el-table-column label="操作" width="180" fixed="right">
              <template #default="{ row }"
                ><el-button type="primary" link size="small" @click="openEdit(row)">编辑</el-button
                ><el-button
                  :type="row.status === 'active' ? 'warning' : 'success'"
                  link
                  size="small"
                  @click="toggleUserStatus(row)"
                  >{{ row.status === 'active' ? '禁用' : '启用' }}</el-button
                ></template
              >
            </el-table-column>
          </el-table>
          <div style="margin-top: 16px; display: flex; justify-content: flex-end">
            <el-pagination
              v-model:current-page="pagination.page"
              small
              layout="total, prev, pager, next"
              :total="users.length"
              :page-size="pagination.pageSize"
            />
          </div>
        </el-tab-pane>
        <el-tab-pane label="审计日志" name="audit">
          <div style="display: flex; gap: 12px; margin-bottom: 16px; flex-wrap: wrap">
            <el-input
              v-model="auditFilter.username"
              placeholder="用户名"
              clearable
              style="width: 150px"
              @clear="loadData"
              @keyup.enter="loadData"
            />
            <el-select
              v-model="auditFilter.operation_type"
              placeholder="操作类型"
              clearable
              style="width: 150px"
              @change="loadData"
            >
              <el-option label="登录" value="login" />
              <el-option label="扫描" value="scan" />
              <el-option label="基线检查" value="baseline_check" />
              <el-option label="病毒检测" value="virus_scan" />
              <el-option label="策略操作" value="policy" />
              <el-option label="配置变更" value="config" />
              <el-option label="密码修改" value="password_change" />
            </el-select>
            <el-date-picker
              v-model="auditFilter.dateRange"
              type="daterange"
              range-separator="至"
              start-placeholder="开始日期"
              end-placeholder="结束日期"
              style="width: 280px"
              value-format="YYYY-MM-DD"
              @change="loadData"
            />
            <el-button type="primary" @click="loadData">查询</el-button>
            <el-button @click="resetAuditFilter">重置</el-button>
            <el-button type="success" size="small" @click="exportAuditLogs">导出CSV</el-button>
          </div>
          <el-table :data="paginatedAudit" size="small" style="width: 100%">
            <el-table-column prop="id" label="日志ID" width="110" />
            <el-table-column prop="user" label="操作用户" width="100" />
            <el-table-column prop="action" label="操作类型" width="100" />
            <el-table-column prop="target" label="操作对象" min-width="150" />
            <el-table-column prop="ip" label="来源IP" width="130" />
            <el-table-column prop="result" label="结果" width="80">
              <template #default="{ row }"
                ><el-tag :type="row.result === 'success' ? 'success' : 'danger'" size="small">{{
                  row.result === 'success' ? '成功' : '失败'
                }}</el-tag></template
              >
            </el-table-column>
            <el-table-column prop="time" label="时间" />
          </el-table>
          <div style="margin-top: 16px; display: flex; justify-content: flex-end">
            <el-pagination
              v-model:current-page="auditPagination.page"
              small
              layout="total, prev, pager, next"
              :total="auditLogs.length"
              :page-size="auditPagination.pageSize"
            />
          </div>
        </el-tab-pane>
      </el-tabs>
    </div>
    <el-dialog v-model="showAddDialog" title="添加用户" width="500px" destroy-on-close>
      <el-form :model="addUser" label-width="80px">
        <el-form-item label="用户名" required
          ><el-input v-model="addUser.username" placeholder="请输入用户名"
        /></el-form-item>
        <el-form-item label="密码" required
          ><el-input v-model="addUser.password" type="password" placeholder="请输入密码" show-password
        /></el-form-item>
        <el-form-item label="角色"
          ><el-select v-model="addUser.role" style="width: 100%"
            ><el-option label="操作员" value="user" /><el-option label="观察员" value="viewer" /><el-option
              label="管理员"
              value="admin" /></el-select
        ></el-form-item>
        <el-form-item label="部门"><el-input v-model="addUser.department" placeholder="请输入部门" /></el-form-item>
      </el-form>
      <template #footer
        ><el-button @click="showAddDialog = false">取消</el-button
        ><el-button type="primary" @click="submitAdd">添加</el-button></template
      >
    </el-dialog>
    <el-dialog v-model="showEditDialog" title="编辑用户" width="500px" destroy-on-close>
      <el-form :model="editUser" label-width="80px">
        <el-form-item label="用户名"><el-input v-model="editUser.username" /></el-form-item>
        <el-form-item label="角色"
          ><el-select v-model="editUser.role" style="width: 100%"
            ><el-option label="管理员" value="admin" /><el-option label="操作员" value="user" /><el-option
              label="观察员"
              value="viewer" /></el-select
        ></el-form-item>
        <el-form-item label="部门"><el-input v-model="editUser.department" /></el-form-item>
      </el-form>
      <template #footer
        ><el-button @click="showEditDialog = false">取消</el-button
        ><el-button type="primary" @click="submitEdit">保存</el-button></template
      >
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue';
import { ElMessage } from 'element-plus';
import { legacyApi } from '@/api';

const loading = ref(false);
const users = ref<Array<Record<string, any>>>([]);
const auditLogs = ref<Array<Record<string, any>>>([]);
const pagination = reactive({ page: 1, pageSize: 10 });
const auditPagination = reactive({ page: 1, pageSize: 10 });
const showAddDialog = ref(false);
const showEditDialog = ref(false);
const activeTab = ref('users');
const editUser = reactive({ id: null as number | null, username: '', role: 'user', department: '', status: 'active' });
const addUser = reactive({ username: '', password: '', role: 'user', department: '' });
const auditFilter = reactive({ username: '', operation_type: '', dateRange: null as string[] | null });
const paginatedUsers = computed(() => {
  const s = (pagination.page - 1) * pagination.pageSize;
  return users.value.slice(s, s + pagination.pageSize);
});
const paginatedAudit = computed(() => {
  const s = (auditPagination.page - 1) * auditPagination.pageSize;
  return auditLogs.value.slice(s, s + auditPagination.pageSize);
});

function demoUsers() {
  const roles = ['admin', 'user', 'viewer'];
  const departments = ['安全运营中心', '网络运维部', '系统管理部', '安全研发部', '合规审计部'];
  return Array.from({ length: 15 }, (_, i) => ({
    id: i + 1,
    username: [
      'admin',
      'zhangsan',
      'lisi',
      'wangwu',
      'zhaoliu',
      'sunqi',
      'zhouba',
      'wujiu',
      'zhengshi',
      'chenyi',
      'lianger',
      'huangsan',
      'qiansi',
      'wuwu',
      'liuliu'
    ][i],
    role: i === 0 ? 'admin' : roles[Math.floor(Math.random() * roles.length)],
    department: departments[Math.floor(Math.random() * departments.length)],
    status: Math.random() > 0.1 ? 'active' : 'disabled',
    createTime: new Date(Date.now() - Math.random() * 365 * 86400000).toLocaleString('zh-CN'),
    lastLogin: new Date(Date.now() - Math.random() * 7 * 86400000).toLocaleString('zh-CN')
  }));
}

function demoAuditLogs() {
  const actions = ['用户登录', '创建策略', '修改配置', '删除设备', '导出报告', '审批策略', '修改用户', '启动扫描'];
  return Array.from({ length: 50 }, (_, i) => ({
    id: 'AUD-' + (7000 + i),
    user: ['admin', 'zhangsan', 'lisi', 'wangwu'][Math.floor(Math.random() * 4)],
    action: actions[Math.floor(Math.random() * actions.length)],
    target: ['策略POL-4001', '用户lisi', '扫描任务SCAN-2001', '系统配置', '设备DEV-5001'][
      Math.floor(Math.random() * 5)
    ],
    ip: `10.0.${Math.floor(Math.random() * 5)}.${Math.floor(Math.random() * 255)}`,
    time: new Date(Date.now() - Math.random() * 30 * 86400000).toLocaleString('zh-CN'),
    result: Math.random() > 0.05 ? 'success' : 'failed'
  }));
}

function resetAuditFilter() {
  auditFilter.username = '';
  auditFilter.operation_type = '';
  auditFilter.dateRange = null;
  loadData();
}

async function loadData() {
  try {
    const [userRes, auditRes] = await Promise.all([
      legacyApi.get('/user/list'),
      (async () => {
        let auditUrl = '/user/audit-logs?page=1&pageSize=50';
        if (auditFilter.username) auditUrl += '&username=' + encodeURIComponent(auditFilter.username);
        if (auditFilter.operation_type) auditUrl += '&operation_type=' + encodeURIComponent(auditFilter.operation_type);
        if (auditFilter.dateRange && auditFilter.dateRange.length === 2) {
          auditUrl += '&start_date=' + auditFilter.dateRange[0] + '&end_date=' + auditFilter.dateRange[1];
        }
        return legacyApi.get(auditUrl);
      })()
    ]);
    if (userRes && userRes.code === 0) {
      users.value = ((userRes.data as any[]) || []).map((u) => ({
        id: u.id,
        username: u.username,
        role: u.role_name || u.role_id,
        department: u.department || '-',
        status: u.status ? 'active' : 'disabled',
        createTime: u.created_at ? new Date(u.created_at).toLocaleString('zh-CN') : '-',
        lastLogin: '-'
      }));
    }
    if (auditRes && auditRes.code === 0) {
      auditLogs.value = ((auditRes.data as any[]) || []).map((l) => ({
        id: 'AUD-' + l.id,
        user: l.username || '-',
        action: l.operation_type || '-',
        target: l.operation_target || '-',
        ip: l.client_ip || '-',
        result: l.result || 'success',
        time: l.created_at ? new Date(l.created_at).toLocaleString('zh-CN') : '-'
      }));
    }
  } catch (e) {
    users.value = demoUsers();
    auditLogs.value = demoAuditLogs();
  }
}

onMounted(() => {
  loadData();
});

function openAdd() {
  Object.assign(addUser, { username: '', password: '', role: 'user', department: '' });
  showAddDialog.value = true;
}
function openEdit(user: Record<string, any>) {
  Object.assign(editUser, {
    id: user.id,
    username: user.username,
    role: user.role,
    department: user.department,
    status: user.status
  });
  showEditDialog.value = true;
}

async function submitAdd() {
  if (!addUser.username || !addUser.password) {
    ElMessage.warning('请填写必填项');
    return;
  }
  try {
    const res = await legacyApi.post('/auth/register', addUser);
    if (res && res.code === 0) {
      users.value.push({
        id: users.value.length + 1,
        username: addUser.username,
        role: addUser.role,
        department: addUser.department,
        status: 'active',
        createTime: new Date().toLocaleString('zh-CN'),
        lastLogin: '-'
      });
      showAddDialog.value = false;
      ElMessage.success('用户已添加');
    } else {
      ElMessage.error(res.message || '添加失败');
    }
  } catch (e) {
    ElMessage.error('添加失败');
  }
}

async function submitEdit() {
  try {
    const roleIdMap: Record<string, number> = { admin: 1, user: 2, viewer: 3 };
    const res = await legacyApi.put('/user/' + editUser.id, {
      username: editUser.username,
      role_id: roleIdMap[editUser.role] || 2,
      department: editUser.department
    });
    if (res && res.code === 0) {
      const user = users.value.find((u) => u.id === editUser.id);
      if (user) {
        user.username = editUser.username;
        user.role = editUser.role;
        user.department = editUser.department;
      }
      showEditDialog.value = false;
      ElMessage.success('用户信息已更新');
    }
  } catch (e) {
    ElMessage.error('更新失败');
  }
}

async function toggleUserStatus(user: Record<string, any>) {
  const newStatus = user.status === 'active' ? 0 : 1;
  try {
    await legacyApi.put('/user/' + user.id, { status: newStatus });
    user.status = newStatus ? 'active' : 'disabled';
    ElMessage.success('用户已' + (newStatus ? '启用' : '禁用'));
  } catch (e) {
    ElMessage.error('操作失败');
  }
}

function getRoleTag(role: string) {
  const map: Record<string, { label: string; type: string }> = {
    admin: { label: '管理员', type: 'danger' },
    user: { label: '操作员', type: 'primary' },
    viewer: { label: '观察员', type: 'info' }
  };
  return map[role] || { label: role, type: 'info' };
}

function exportAuditLogs() {
  if (auditLogs.value.length === 0) return;
  const headers = '用户,操作类型,操作目标,IP,结果,时间\n';
  const rows = auditLogs.value.map((l) => `${l.user},${l.action},${l.target},${l.ip},${l.result},${l.time}`).join('\n');
  const blob = new Blob(['\uFEFF' + headers + rows], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'audit_logs.csv';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  ElMessage.success('审计日志已导出');
}
</script>
