// frontend-app/src/views/Defense.vue
<template>
  <div v-loading="loading">
    <div class="page-header">
      <div>
        <div class="page-title">自动化防御</div>
        <div class="page-desc">安全策略管理与自动化响应</div>
      </div>
      <el-button type="primary" size="small" @click="openCreateDialog"
        ><el-icon><Plus /></el-icon> 创建策略</el-button
      >
    </div>
    <div class="chart-card">
      <el-tabs v-model="activeTab">
        <el-tab-pane label="策略列表" name="policies">
          <el-table :data="paginatedPolicies" size="small" style="width: 100%">
            <el-table-column prop="id" label="ID" width="110" />
            <el-table-column prop="name" label="策略名称" min-width="140" />
            <el-table-column prop="condition" label="触发条件" min-width="200" show-overflow-tooltip />
            <el-table-column prop="action" label="执行动作" width="130" />
            <el-table-column prop="status" label="状态" width="90">
              <template #default="{ row }"
                ><el-tag :type="getStatusTag(row.status).type" size="small">{{
                  getStatusTag(row.status).label
                }}</el-tag></template
              >
            </el-table-column>
            <el-table-column label="冷却时间" width="90"
              ><template #default="{ row }">{{ row.cooldown }}s</template></el-table-column
            >
            <el-table-column label="无人值守" width="80">
              <template #default="{ row }"
                ><el-tag :type="row.unattended ? 'success' : 'info'" size="small">{{
                  row.unattended ? '是' : '否'
                }}</el-tag></template
              >
            </el-table-column>
            <el-table-column label="操作" width="220" fixed="right">
              <template #default="{ row }">
                <el-switch
                  v-if="row.status !== 'pending_approval'"
                  v-model="row.status"
                  active-value="active"
                  inactive-value="inactive"
                  style="margin-right: 8px"
                  @change="togglePolicy(row)"
                />
                <el-button
                  v-if="row.status === 'pending_approval'"
                  type="success"
                  link
                  size="small"
                  @click="approvePolicy(row.id, true)"
                  >通过</el-button
                >
                <el-button
                  v-if="row.status === 'pending_approval'"
                  type="danger"
                  link
                  size="small"
                  @click="approvePolicy(row.id, false)"
                  >驳回</el-button
                >
                <el-button type="danger" link size="small" @click="deletePolicy(row.id)">删除</el-button>
              </template>
            </el-table-column>
          </el-table>
          <div style="margin-top: 16px; display: flex; justify-content: flex-end">
            <el-pagination
              v-model:current-page="policyPagination.page"
              small
              layout="total, prev, pager, next"
              :total="policies.length"
              :page-size="policyPagination.pageSize"
            />
          </div>
        </el-tab-pane>
        <el-tab-pane name="approvals">
          <template #label
            ><span
              >待审批
              <el-badge :value="pendingApprovals.length" :hidden="pendingApprovals.length === 0" type="warning" /></span
          ></template>
          <el-table v-if="pendingApprovals.length > 0" :data="pendingApprovals" size="small" style="width: 100%">
            <el-table-column prop="name" label="策略名称" min-width="140" />
            <el-table-column prop="condition" label="触发条件" min-width="180" show-overflow-tooltip />
            <el-table-column prop="action" label="执行动作" width="130" />
            <el-table-column prop="requesterName" label="申请人" width="100" />
            <el-table-column prop="requestDate" label="申请时间" width="160" />
            <el-table-column label="操作" width="150" fixed="right">
              <template #default="{ row }">
                <el-button type="success" size="small" @click="handleApproval(row.approvalId, true)">通过</el-button>
                <el-button type="danger" size="small" @click="handleApproval(row.approvalId, false)">驳回</el-button>
              </template>
            </el-table-column>
          </el-table>
          <el-empty v-else description="暂无待审批策略" />
        </el-tab-pane>
        <el-tab-pane label="动作日志" name="logs">
          <el-table :data="paginatedLogs" size="small" style="width: 100%">
            <el-table-column prop="id" label="日志ID" width="110" />
            <el-table-column prop="policyName" label="策略名称" width="130" />
            <el-table-column prop="action" label="执行动作" width="100" />
            <el-table-column prop="target" label="目标" width="150" />
            <el-table-column prop="result" label="结果" width="80">
              <template #default="{ row }"
                ><el-tag :type="getResultTag(row.result).type" size="small">{{
                  getResultTag(row.result).label
                }}</el-tag></template
              >
            </el-table-column>
            <el-table-column prop="time" label="时间" />
          </el-table>
          <div style="margin-top: 16px; display: flex; justify-content: flex-end">
            <el-pagination
              v-model:current-page="logPagination.page"
              small
              layout="total, prev, pager, next"
              :total="actionLogs.length"
              :page-size="logPagination.pageSize"
            />
          </div>
        </el-tab-pane>
      </el-tabs>
    </div>
    <el-dialog v-model="showCreateDialog" title="创建防御策略" width="600px" destroy-on-close>
      <el-form :model="newPolicy" label-width="100px">
        <el-form-item label="策略名称" required
          ><el-input v-model="newPolicy.name" placeholder="请输入策略名称"
        /></el-form-item>
        <el-form-item label="条件类型"
          ><el-select v-model="newPolicy.conditionType" style="width: 100%"
            ><el-option label="阈值触发" value="threshold" /><el-option label="规则匹配" value="rule" /><el-option
              label="异常检测"
              value="anomaly" /><el-option label="威胁情报" value="threat_intel" /></el-select
        ></el-form-item>
        <el-form-item label="条件参数"
          ><el-input v-model="newPolicy.conditionValue" placeholder="例: 5分钟内>10次失败"
        /></el-form-item>
        <el-form-item label="动作类型"
          ><el-select v-model="newPolicy.actionType" style="width: 100%"
            ><el-option label="封禁IP" value="block_ip" /><el-option label="隔离主机" value="isolate_host" /><el-option
              label="阻断连接"
              value="block_connection" /><el-option label="发送告警" value="alert" /><el-option
              label="记录日志"
              value="log" /></el-select
        ></el-form-item>
        <el-form-item label="动作参数"
          ><el-input v-model="newPolicy.actionParam" placeholder="例: 封禁时长24h"
        /></el-form-item>
        <el-form-item label="冷却时间"
          ><el-input-number v-model="newPolicy.cooldown" :min="60" :max="86400" :step="60" />
          <span style="margin-left: 8px; color: rgba(255, 255, 255, 0.4)">秒</span></el-form-item
        >
        <el-form-item label="无人值守"
          ><el-switch v-model="newPolicy.unattended" /><span
            style="margin-left: 8px; color: rgba(255, 255, 255, 0.4); font-size: 12px"
            >开启后策略将自动执行无需审批</span
          ></el-form-item
        >
      </el-form>
      <template #footer
        ><el-button @click="showCreateDialog = false">取消</el-button
        ><el-button type="primary" @click="createPolicy">创建</el-button></template
      >
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { legacyApi } from '@/api';

const loading = ref(false);
const policies = ref<Array<Record<string, any>>>([]);
const actionLogs = ref<Array<Record<string, any>>>([]);
const pendingApprovals = ref<Array<Record<string, any>>>([]);
const showCreateDialog = ref(false);
const activeTab = ref('policies');
const policyPagination = reactive({ page: 1, pageSize: 10 });
const logPagination = reactive({ page: 1, pageSize: 10 });
const newPolicy = reactive({
  name: '',
  conditionType: 'threshold',
  conditionValue: '',
  actionType: 'block_ip',
  actionParam: '',
  cooldown: 300,
  unattended: false
});
const paginatedPolicies = computed(() => {
  const s = (policyPagination.page - 1) * policyPagination.pageSize;
  return policies.value.slice(s, s + policyPagination.pageSize);
});
const paginatedLogs = computed(() => {
  const s = (logPagination.page - 1) * logPagination.pageSize;
  return actionLogs.value.slice(s, s + logPagination.pageSize);
});

function demoDefensePolicies() {
  const conditions = [
    '检测到暴力破解(5分钟内>10次)',
    '检测到DDoS攻击',
    '检测到恶意文件上传',
    '检测到SQL注入',
    '检测到异常端口扫描',
    '检测到未授权访问尝试'
  ];
  const actions = ['自动封禁IP(24h)', '发送告警通知', '隔离受感染主机', '阻断连接', '记录日志'];
  const statuses = ['active', 'inactive', 'pending_approval'];
  return Array.from({ length: 15 }, (_, i) => ({
    id: 'POL-' + (4000 + i),
    name: [
      '暴力破解防护',
      'DDoS防护',
      '恶意文件拦截',
      'SQL注入防护',
      '端口扫描检测',
      '未授权访问拦截',
      '异常流量监控',
      '恶意IP黑名单',
      '弱密码检测',
      '提权行为监控',
      '反弹Shell检测',
      'Webshell检测',
      '异常DNS检测',
      '横向移动检测',
      '数据泄露防护'
    ][i],
    condition: conditions[Math.floor(Math.random() * conditions.length)],
    action: actions[Math.floor(Math.random() * actions.length)],
    status: statuses[Math.floor(Math.random() * statuses.length)],
    cooldown: [300, 600, 900, 1800, 3600][Math.floor(Math.random() * 5)],
    unattended: Math.random() > 0.5,
    createTime: new Date(Date.now() - Math.random() * 60 * 86400000).toLocaleString('zh-CN')
  }));
}

function demoActionLogs() {
  const actions = ['封禁IP', '隔离主机', '阻断连接', '发送告警', '更新规则'];
  return Array.from({ length: 40 }, (_, i) => ({
    id: 'LOG-' + (6000 + i),
    policyName: ['暴力破解防护', 'DDoS防护', '恶意文件拦截', 'SQL注入防护'][Math.floor(Math.random() * 4)],
    action: actions[Math.floor(Math.random() * actions.length)],
    target: `192.168.${Math.floor(Math.random() * 5)}.${Math.floor(Math.random() * 255)}`,
    result: Math.random() > 0.1 ? 'success' : 'failed',
    time: new Date(Date.now() - Math.random() * 7 * 86400000).toLocaleString('zh-CN'),
    detail: '策略自动触发执行'
  }));
}

async function loadData() {
  try {
    const [polRes, logRes, approvalRes] = await Promise.all([
      legacyApi.get('/defense/policies'),
      legacyApi.get('/defense/action-logs'),
      legacyApi.get('/defense/pending-approvals')
    ]);
    if (polRes && polRes.code === 0) {
      policies.value = ((polRes.data as any[]) || []).map((p) => ({
        id: p.id,
        name: p.name,
        condition: Array.isArray(p.conditions)
          ? p.conditions.map((c: any) => c.field || c.fact).join(', ')
          : p.description || '-',
        action: Array.isArray(p.actions) ? p.actions.map((a: any) => a.type).join(', ') : '-',
        status: p.approval_status === 'pending' ? 'pending_approval' : p.enabled ? 'active' : 'inactive',
        cooldown: p.cooldown,
        unattended: !!p.unattended,
        createTime: p.created_at ? new Date(p.created_at).toLocaleString('zh-CN') : '-'
      }));
    }
    if (logRes && logRes.code === 0) {
      actionLogs.value = ((logRes.data as any[]) || []).map((l) => ({
        id: 'LOG-' + l.id,
        policyName: '策略#' + (l.policy_id || '-'),
        action: l.action_type || '-',
        target: l.action_detail || '-',
        result: l.result || 'success',
        time: l.executed_at ? new Date(l.executed_at).toLocaleString('zh-CN') : '-'
      }));
    }
    if (approvalRes && approvalRes.code === 0) {
      pendingApprovals.value = ((approvalRes.data as any[]) || []).map((a) => ({
        approvalId: a.approval_id,
        policyId: a.id,
        name: a.name,
        condition: Array.isArray(a.conditions)
          ? a.conditions.map((c: any) => c.field || c.fact).join(', ')
          : a.description || '-',
        action: Array.isArray(a.actions) ? a.actions.map((a2: any) => a2.type).join(', ') : '-',
        requesterName: a.requester_name || '未知',
        requestDate: a.request_date ? new Date(a.request_date).toLocaleString('zh-CN') : '-'
      }));
    }
  } catch (e) {
    policies.value = demoDefensePolicies();
    actionLogs.value = demoActionLogs();
  }
}

onMounted(() => {
  loadData();
});

function openCreateDialog() {
  Object.assign(newPolicy, {
    name: '',
    conditionType: 'threshold',
    conditionValue: '',
    actionType: 'block_ip',
    actionParam: '',
    cooldown: 300,
    unattended: false
  });
  showCreateDialog.value = true;
}

async function createPolicy() {
  if (!newPolicy.name) {
    ElMessage.warning('请输入策略名称');
    return;
  }
  loading.value = true;
  try {
    const payload = {
      name: newPolicy.name,
      description: newPolicy.conditionType + ': ' + newPolicy.conditionValue,
      conditions: [{ field: newPolicy.conditionType, operator: 'equals', value: newPolicy.conditionValue }],
      actions: [{ type: newPolicy.actionType, params: { detail: newPolicy.actionParam } }],
      cooldown: newPolicy.cooldown,
      unattended: newPolicy.unattended
    };
    const res = await legacyApi.post('/defense/policies', payload);
    if (res && res.code === 0) {
      policies.value.unshift({
        id: (res.data as any).id,
        name: newPolicy.name,
        condition: newPolicy.conditionType + ': ' + newPolicy.conditionValue,
        action: newPolicy.actionType,
        status: 'active',
        cooldown: newPolicy.cooldown,
        unattended: newPolicy.unattended,
        createTime: new Date().toLocaleString('zh-CN')
      });
      showCreateDialog.value = false;
      ElMessage.success('策略创建成功');
    }
  } catch (e) {
    ElMessage.error('创建失败');
  }
  loading.value = false;
}

async function togglePolicy(policy: Record<string, any>) {
  const newEnabled = policy.status === 'active';
  try {
    await legacyApi.put('/defense/policies/' + policy.id, { enabled: newEnabled });
  } catch (e) {
    /* ignore */
  }
  policy.status = newEnabled ? 'active' : 'inactive';
  ElMessage.success('策略已' + (newEnabled ? '启用' : '禁用'));
}

async function deletePolicy(id: string) {
  try {
    await ElMessageBox.confirm('确定要删除此策略吗？', '确认', { type: 'warning' });
  } catch (e) {
    return;
  }
  try {
    await legacyApi.delete('/defense/policies/' + id);
  } catch (e) {
    /* ignore */
  }
  policies.value = policies.value.filter((p) => p.id !== id);
  ElMessage.success('已删除');
}

async function approvePolicy(id: string, approved: boolean) {
  try {
    await legacyApi.post('/defense/approvals/' + id, {
      status: approved ? 'approved' : 'rejected',
      risk_assessment: approved ? '审批通过' : '审批驳回'
    });
  } catch (e) {
    /* ignore */
  }
  const policy = policies.value.find((p) => p.id === id);
  if (policy) policy.status = approved ? 'active' : 'inactive';
  ElMessage.success(approved ? '已审批通过' : '已驳回');
}

async function handleApproval(approvalId: string, approved: boolean) {
  try {
    await legacyApi.post('/defense/approvals/' + approvalId, {
      status: approved ? 'approved' : 'rejected',
      risk_assessment: approved ? '审批通过' : '审批驳回'
    });
    pendingApprovals.value = pendingApprovals.value.filter((a) => a.approvalId !== approvalId);
    ElMessage.success(approved ? '策略已审批通过' : '策略已驳回');
    loadData();
  } catch (e) {
    ElMessage.error('审批操作失败');
  }
}

function getStatusTag(status: string) {
  const map: Record<string, { label: string; type: string }> = {
    active: { label: '已启用', type: 'success' },
    inactive: { label: '已禁用', type: 'info' },
    pending_approval: { label: '待审批', type: 'warning' }
  };
  return map[status] || { label: status, type: 'info' };
}

function getResultTag(result: string) {
  return result === 'success' ? { label: '成功', type: 'success' } : { label: '失败', type: 'danger' };
}
</script>

// frontend-react/src/pages/Defense.tsx
import { useEffect, useMemo, useState } from 'react';
import { defenseApi } from '@/api';
import type { ActionLog, AutoPolicy, PolicyApproval } from '@/api';
import Badge from '@/components/ui/badge';
import Button from '@/components/ui/button';
import Dialog from '@/components/ui/dialog';
import { Table } from '@/components/ui/table';
import { useToast } from '@/components/ui/use-toast';

const PAGE_SIZE = 10;

const fieldCls =
  'rounded-md border border-cyan-500/20 bg-[#1a2340] px-3 py-2 text-sm text-gray-300 outline-none transition-colors placeholder:text-gray-500 focus:border-cyan-500/60';

type TabKey = 'policies' | 'approvals' | 'logs';

interface TagInfo {
  label: string;
  variant: 'default' | 'success' | 'warning' | 'danger';
}

interface PolicyForm {
  name: string;
  description: string;
  conditionsJson: string;
  actionsJson: string;
  cooldown: number;
  unattended: boolean;
  enabled: boolean;
}

const EMPTY_FORM: PolicyForm = {
  name: '',
  description: '',
  conditionsJson: '[]',
  actionsJson: '[]',
  cooldown: 300,
  unattended: false,
  enabled: true
};

function isEnabled(v: number | boolean | undefined): boolean {
  return v !== 0 && v !== false && v !== undefined;
}

function enabledTag(enabled: boolean): TagInfo {
  return enabled ? { label: '已启用', variant: 'success' } : { label: '已禁用', variant: 'default' };
}

function approvalTag(status?: string): TagInfo {
  if (status === 'pending') return { label: '待审批', variant: 'warning' };
  if (status === 'approved') return { label: '已审批', variant: 'success' };
  if (status === 'rejected') return { label: '已驳回', variant: 'danger' };
  return { label: status || '-', variant: 'default' };
}

function resultTag(result?: string): TagInfo {
  return result === 'success' ? { label: '成功', variant: 'success' } : { label: '失败', variant: 'danger' };
}

/** 兼容后端返回的数组或 JSON 字符串，统一转为数组 */
function normalizeList<T>(v: unknown): T[] {
  if (Array.isArray(v)) return v as T[];
  if (typeof v === 'string') {
    try {
      const parsed = JSON.parse(v);
      if (Array.isArray(parsed)) return parsed as T[];
    } catch {
      // 非 JSON 字符串，返回空数组
    }
  }
  return [];
}

function conditionsText(v: unknown, fallback?: string): string {
  const list = normalizeList<{ field?: string; fact?: string }>(v);
  if (list.length > 0) {
    return list.map((c) => c.field || c.fact || JSON.stringify(c)).join('; ');
  }
  return fallback || '-';
}

function actionsText(v: unknown): string {
  const list = normalizeList<{ type?: string }>(v);
  if (list.length > 0) {
    return list.map((a) => a.type || JSON.stringify(a)).join(', ');
  }
  return '-';
}

function formatTime(t?: string): string {
  return t ? new Date(t).toLocaleString('zh-CN') : '-';
}

function ToggleSwitch({
  checked,
  disabled,
  onChange
}: {
  checked: boolean;
  disabled?: boolean;
  onChange: (v: boolean) => void;
}) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      disabled={disabled}
      onClick={() => onChange(!checked)}
      className={`relative inline-flex h-5 w-9 shrink-0 items-center rounded-full transition-colors disabled:cursor-not-allowed disabled:opacity-40 ${
        checked ? 'bg-green-500' : 'bg-gray-600'
      }`}
    >
      <span
        className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
          checked ? 'translate-x-[18px]' : 'translate-x-0.5'
        }`}
      />
    </button>
  );
}

function Pagination({
  page,
  total,
  pageSize,
  onChange
}: {
  page: number;
  total: number;
  pageSize: number;
  onChange: (p: number) => void;
}) {
  const pages = Math.max(1, Math.ceil(total / pageSize));
  if (pages <= 1) return null;
  return (
    <div className="mt-4 flex items-center justify-end gap-2 text-xs text-gray-400">
      <span>共 {total} 条</span>
      <button
        type="button"
        disabled={page <= 1}
        onClick={() => onChange(page - 1)}
        className="rounded border border-white/10 px-2 py-1 transition-colors hover:border-cyan-500/40 disabled:opacity-40"
      >
        上一页
      </button>
      <span className="px-1">
        {page} / {pages}
      </span>
      <button
        type="button"
        disabled={page >= pages}
        onClick={() => onChange(page + 1)}
        className="rounded border border-white/10 px-2 py-1 transition-colors hover:border-cyan-500/40 disabled:opacity-40"
      >
        下一页
      </button>
    </div>
  );
}

export default function Defense() {
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState<TabKey>('policies');
  const [loading, setLoading] = useState(false);

  const [policies, setPolicies] = useState<AutoPolicy[]>([]);
  const [approvals, setApprovals] = useState<PolicyApproval[]>([]);
  const [logs, setLogs] = useState<ActionLog[]>([]);

  const [policyPage, setPolicyPage] = useState(1);
  const [logPage, setLogPage] = useState(1);

  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form, setForm] = useState<PolicyForm>(EMPTY_FORM);
  const [saving, setSaving] = useState(false);

  const [deleteTarget, setDeleteTarget] = useState<AutoPolicy | null>(null);
  const [deleting, setDeleting] = useState(false);

  async function loadData() {
    setLoading(true);
    try {
      const [pol, app, logRes] = await Promise.all([
        defenseApi.policies(),
        defenseApi.pendingApprovals(),
        defenseApi.actionLogs({ page: 1, pageSize: 100 })
      ]);
      setPolicies(pol || []);
      setApprovals(app || []);
      setLogs(logRes?.list || []);
    } catch {
      setPolicies([]);
      setApprovals([]);
      setLogs([]);
    }
    setLoading(false);
  }

  useEffect(() => {
    loadData();
  }, []);

  const paginatedPolicies = useMemo(() => {
    const s = (policyPage - 1) * PAGE_SIZE;
    return policies.slice(s, s + PAGE_SIZE);
  }, [policies, policyPage]);

  const paginatedLogs = useMemo(() => {
    const s = (logPage - 1) * PAGE_SIZE;
    return logs.slice(s, s + PAGE_SIZE);
  }, [logs, logPage]);

  function openCreate() {
    setEditingId(null);
    setForm({ ...EMPTY_FORM });
    setDialogOpen(true);
  }

  function openEdit(p: AutoPolicy) {
    setEditingId(p.id);
    setForm({
      name: p.name,
      description: p.description || '',
      conditionsJson: JSON.stringify(normalizeList(p.conditions), null, 2),
      actionsJson: JSON.stringify(normalizeList(p.actions), null, 2),
      cooldown: p.cooldown || 300,
      unattended: !!p.unattended,
      enabled: isEnabled(p.enabled)
    });
    setDialogOpen(true);
  }

  async function savePolicy() {
    if (!form.name.trim()) {
      toast({ title: '请输入策略名称', variant: 'warning' });
      return;
    }
    let conditions: Array<Record<string, unknown>>;
    let actions: Array<Record<string, unknown>>;
    try {
      conditions = JSON.parse(form.conditionsJson || '[]');
    } catch {
      toast({ title: '触发条件 JSON 格式不正确', variant: 'error' });
      return;
    }
    try {
      actions = JSON.parse(form.actionsJson || '[]');
    } catch {
      toast({ title: '执行动作 JSON 格式不正确', variant: 'error' });
      return;
    }
    if (!Array.isArray(conditions) || !Array.isArray(actions)) {
      toast({ title: '条件与动作需为 JSON 数组', variant: 'error' });
      return;
    }
    const payload = {
      name: form.name.trim(),
      description: form.description.trim() || undefined,
      conditions,
      actions,
      cooldown: form.cooldown || 300,
      unattended: form.unattended,
      enabled: form.enabled
    };
    setSaving(true);
    try {
      if (editingId !== null) {
        await defenseApi.update(editingId, payload);
        toast({ title: '策略更新成功', variant: 'success' });
      } else {
        await defenseApi.create(payload);
        toast({ title: '策略创建成功', variant: 'success' });
      }
      setDialogOpen(false);
      loadData();
    } catch {
      // http 拦截器已提示
    }
    setSaving(false);
  }

  async function togglePolicy(p: AutoPolicy) {
    const enabled = !isEnabled(p.enabled);
    try {
      await defenseApi.toggle(p.id, enabled);
      toast({ title: `策略已${enabled ? '启用' : '禁用'}`, variant: 'success' });
      loadData();
    } catch {
      // http 拦截器已提示
    }
  }

  async function confirmDelete() {
    if (!deleteTarget) return;
    setDeleting(true);
    try {
      await defenseApi.remove(deleteTarget.id);
      toast({ title: '策略已删除', variant: 'success' });
      setDeleteTarget(null);
      loadData();
    } catch {
      // http 拦截器已提示
    }
    setDeleting(false);
  }

  async function reviewApproval(a: PolicyApproval, approved: boolean) {
    if (a.approval_id === undefined) return;
    try {
      await defenseApi.approve(a.approval_id, approved ? 'approved' : 'rejected', approved ? '审批通过' : '审批驳回');
      toast({ title: approved ? '已审批通过' : '已驳回', variant: 'success' });
      loadData();
    } catch {
      // http 拦截器已提示
    }
  }

  const tabs: Array<[TabKey, string]> = [
    ['policies', '策略列表'],
    ['approvals', '待审批'],
    ['logs', '动作日志']
  ];

  return (
    <div className="space-y-5">
      {/* 页头 */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-white">自动化防御</h2>
          <p className="mt-1 text-sm text-gray-400">安全策略管理与自动化响应</p>
        </div>
        <Button size="sm" onClick={openCreate}>
          创建策略
        </Button>
      </div>

      <div className="rounded-lg border border-cyan-500/20 bg-[#16213e]/80 p-5">
        {/* Tabs */}
        <div className="mb-4 flex gap-6 border-b border-white/10">
          {tabs.map(([key, label]) => (
            <button
              key={key}
              type="button"
              onClick={() => setActiveTab(key)}
              className={`flex items-center gap-2 border-b-2 pb-2 text-sm transition-colors ${
                activeTab === key
                  ? 'border-cyan-400 text-cyan-300'
                  : 'border-transparent text-gray-400 hover:text-gray-200'
              }`}
            >
              {label}
              {key === 'approvals' && approvals.length > 0 && (
                <span className="rounded-full bg-amber-500/20 px-1.5 py-0.5 text-xs text-amber-400">
                  {approvals.length}
                </span>
              )}
            </button>
          ))}
        </div>

        {/* 策略列表 */}
        {activeTab === 'policies' && (
          <>
            <Table>
              <thead>
                <tr className="border-b border-cyan-500/20 text-left text-xs text-cyan-200/70">
                  <th className="px-2 py-2 font-medium">ID</th>
                  <th className="px-2 py-2 font-medium">策略名称</th>
                  <th className="px-2 py-2 font-medium">描述</th>
                  <th className="px-2 py-2 font-medium">触发条件</th>
                  <th className="px-2 py-2 font-medium">执行动作</th>
                  <th className="px-2 py-2 font-medium">冷却时间</th>
                  <th className="px-2 py-2 font-medium">无人值守</th>
                  <th className="px-2 py-2 font-medium">启用</th>
                  <th className="px-2 py-2 font-medium">审批状态</th>
                  <th className="px-2 py-2 font-medium">操作</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {paginatedPolicies.map((p) => {
                  const enabled = isEnabled(p.enabled);
                  const pending = p.approval_status === 'pending';
                  return (
                    <tr key={p.id} className="hover:bg-white/5">
                      <td className="px-2 py-2 font-mono text-xs text-gray-400">{p.id}</td>
                      <td className="px-2 py-2 text-gray-300">{p.name}</td>
                      <td className="max-w-[200px] truncate px-2 py-2 text-gray-400" title={p.description || ''}>
                        {p.description || '-'}
                      </td>
                      <td
                        className="max-w-[220px] truncate px-2 py-2 text-gray-400"
                        title={conditionsText(p.conditions)}
                      >
                        {conditionsText(p.conditions)}
                      </td>
                      <td className="max-w-[160px] truncate px-2 py-2 text-gray-400" title={actionsText(p.actions)}>
                        {actionsText(p.actions)}
                      </td>
                      <td className="px-2 py-2 text-gray-400">{p.cooldown}s</td>
                      <td className="px-2 py-2">
                        <Badge variant={p.unattended ? 'success' : 'default'}>{p.unattended ? '是' : '否'}</Badge>
                      </td>
                      <td className="px-2 py-2">
                        <div className="flex items-center gap-2">
                          <ToggleSwitch checked={enabled} disabled={pending} onChange={() => togglePolicy(p)} />
                          <Badge variant={enabledTag(enabled).variant}>{enabledTag(enabled).label}</Badge>
                        </div>
                      </td>
                      <td className="px-2 py-2">
                        <Badge variant={approvalTag(p.approval_status).variant}>
                          {approvalTag(p.approval_status).label}
                        </Badge>
                      </td>
                      <td className="px-2 py-2">
                        <div className="flex gap-3">
                          <button
                            type="button"
                            onClick={() => openEdit(p)}
                            className="text-xs text-cyan-400 transition-colors hover:text-cyan-300"
                          >
                            编辑
                          </button>
                          <button
                            type="button"
                            onClick={() => setDeleteTarget(p)}
                            className="text-xs text-red-400 transition-colors hover:text-red-300"
                          >
                            删除
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
                {paginatedPolicies.length === 0 && (
                  <tr>
                    <td colSpan={10} className="px-2 py-6 text-center text-gray-500">
                      {loading ? '加载中…' : '暂无防御策略'}
                    </td>
                  </tr>
                )}
              </tbody>
            </Table>
            <Pagination page={policyPage} total={policies.length} pageSize={PAGE_SIZE} onChange={setPolicyPage} />
          </>
        )}

        {/* 待审批 */}
        {activeTab === 'approvals' && (
          <>
            {approvals.length === 0 ? (
              <div className="py-10 text-center text-sm text-gray-500">{loading ? '加载中…' : '暂无待审批策略'}</div>
            ) : (
              <Table>
                <thead>
                  <tr className="border-b border-cyan-500/20 text-left text-xs text-cyan-200/70">
                    <th className="px-2 py-2 font-medium">策略ID</th>
                    <th className="px-2 py-2 font-medium">策略名称</th>
                    <th className="px-2 py-2 font-medium">触发条件</th>
                    <th className="px-2 py-2 font-medium">执行动作</th>
                    <th className="px-2 py-2 font-medium">申请人</th>
                    <th className="px-2 py-2 font-medium">申请时间</th>
                    <th className="px-2 py-2 font-medium">风险评估</th>
                    <th className="px-2 py-2 font-medium">操作</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {approvals.map((a) => (
                    <tr key={a.approval_id ?? a.id} className="hover:bg-white/5">
                      <td className="px-2 py-2 font-mono text-xs text-gray-400">{a.id ?? '-'}</td>
                      <td className="px-2 py-2 text-gray-300">{a.name || '-'}</td>
                      <td
                        className="max-w-[220px] truncate px-2 py-2 text-gray-400"
                        title={conditionsText(a.conditions, a.description)}
                      >
                        {conditionsText(a.conditions, a.description)}
                      </td>
                      <td className="max-w-[160px] truncate px-2 py-2 text-gray-400" title={actionsText(a.actions)}>
                        {actionsText(a.actions)}
                      </td>
                      <td className="px-2 py-2 text-gray-400">{a.requester_name || '未知'}</td>
                      <td className="px-2 py-2 text-gray-400">{formatTime(a.request_date || a.created_at)}</td>
                      <td className="max-w-[200px] truncate px-2 py-2 text-gray-400" title={a.risk_assessment || ''}>
                        {a.risk_assessment || '-'}
                      </td>
                      <td className="px-2 py-2">
                        <div className="flex gap-2">
                          <Button size="sm" onClick={() => reviewApproval(a, true)}>
                            通过
                          </Button>
                          <Button size="sm" variant="destructive" onClick={() => reviewApproval(a, false)}>
                            驳回
                          </Button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </Table>
            )}
          </>
        )}

        {/* 动作日志 */}
        {activeTab === 'logs' && (
          <>
            <Table>
              <thead>
                <tr className="border-b border-cyan-500/20 text-left text-xs text-cyan-200/70">
                  <th className="px-2 py-2 font-medium">日志ID</th>
                  <th className="px-2 py-2 font-medium">策略名称</th>
                  <th className="px-2 py-2 font-medium">动作类型</th>
                  <th className="px-2 py-2 font-medium">动作详情</th>
                  <th className="px-2 py-2 font-medium">结果</th>
                  <th className="px-2 py-2 font-medium">执行时间</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {paginatedLogs.map((l) => (
                  <tr key={l.id} className="hover:bg-white/5">
                    <td className="px-2 py-2 font-mono text-xs text-gray-400">{l.id}</td>
                    <td className="px-2 py-2 text-gray-300">
                      {l.policy_name || (l.policy_id !== undefined ? `策略#${l.policy_id}` : '-')}
                    </td>
                    <td className="px-2 py-2 text-gray-400">{l.action_type || '-'}</td>
                    <td className="max-w-[300px] truncate px-2 py-2 text-gray-400" title={l.action_detail || ''}>
                      {l.action_detail || '-'}
                    </td>
                    <td className="px-2 py-2">
                      <Badge variant={resultTag(l.result).variant}>{resultTag(l.result).label}</Badge>
                    </td>
                    <td className="px-2 py-2 text-gray-400">{formatTime(l.executed_at)}</td>
                  </tr>
                ))}
                {paginatedLogs.length === 0 && (
                  <tr>
                    <td colSpan={6} className="px-2 py-6 text-center text-gray-500">
                      {loading ? '加载中…' : '暂无动作日志'}
                    </td>
                  </tr>
                )}
              </tbody>
            </Table>
            <Pagination page={logPage} total={logs.length} pageSize={PAGE_SIZE} onChange={setLogPage} />
          </>
        )}
      </div>

      {/* 新建/编辑策略弹窗 */}
      <Dialog
        open={dialogOpen}
        onOpenChange={(open) => !open && setDialogOpen(false)}
        title={editingId !== null ? '编辑防御策略' : '创建防御策略'}
        footer={
          <>
            <Button size="sm" variant="outline" onClick={() => setDialogOpen(false)}>
              取消
            </Button>
            <Button size="sm" disabled={saving} onClick={savePolicy}>
              {saving ? '保存中…' : '保存'}
            </Button>
          </>
        }
      >
        <div className="max-h-[60vh] space-y-4 overflow-y-auto pr-1">
          <div>
            <label className="mb-1 block text-xs text-gray-400">策略名称</label>
            <input
              className={`${fieldCls} w-full`}
              value={form.name}
              placeholder="请输入策略名称"
              onChange={(e) => setForm({ ...form, name: e.target.value })}
            />
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-400">描述</label>
            <input
              className={`${fieldCls} w-full`}
              value={form.description}
              placeholder="策略描述（可选）"
              onChange={(e) => setForm({ ...form, description: e.target.value })}
            />
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-400">
              触发条件（JSON 数组，例：[{'{'} "field": "login_failures", "operator": "greaterThan", "value": 10 {'}'}{' '}
              ]）
            </label>
            <textarea
              className={`${fieldCls} w-full resize-none font-mono text-xs`}
              rows={3}
              value={form.conditionsJson}
              onChange={(e) => setForm({ ...form, conditionsJson: e.target.value })}
            />
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-400">
              执行动作（JSON 数组，例：[{'{'} "type": "block_ip", "params": {'{'} "duration": 3600 {'}'} {'}'} ]）
            </label>
            <textarea
              className={`${fieldCls} w-full resize-none font-mono text-xs`}
              rows={3}
              value={form.actionsJson}
              onChange={(e) => setForm({ ...form, actionsJson: e.target.value })}
            />
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-400">冷却时间（秒）</label>
            <input
              type="number"
              min={60}
              max={86400}
              step={60}
              className={`${fieldCls} w-full`}
              value={form.cooldown}
              onChange={(e) => setForm({ ...form, cooldown: Number(e.target.value) })}
            />
          </div>
          <div className="space-y-3 pt-1">
            <label className="flex cursor-pointer items-center gap-2 text-sm text-gray-300">
              <input
                type="checkbox"
                checked={form.unattended}
                onChange={(e) => setForm({ ...form, unattended: e.target.checked })}
                className="h-4 w-4 accent-cyan-500"
              />
              无人值守（开启后策略将自动执行无需审批）
            </label>
            <label className="flex cursor-pointer items-center gap-2 text-sm text-gray-300">
              <input
                type="checkbox"
                checked={form.enabled}
                onChange={(e) => setForm({ ...form, enabled: e.target.checked })}
                className="h-4 w-4 accent-cyan-500"
              />
              立即启用
            </label>
          </div>
        </div>
      </Dialog>

      {/* 删除确认 */}
      <Dialog open={!!deleteTarget} onOpenChange={(open) => !open && setDeleteTarget(null)} title="删除确认">
        <p className="text-sm text-gray-600">确定要删除策略「{deleteTarget?.name}」吗？删除后无法恢复。</p>
        <div className="mt-4 flex justify-end gap-2">
          <Button size="sm" variant="outline" onClick={() => setDeleteTarget(null)}>
            取消
          </Button>
          <Button size="sm" variant="destructive" disabled={deleting} onClick={confirmDelete}>
            {deleting ? '删除中…' : '删除'}
          </Button>
        </div>
      </Dialog>
    </div>
  );
}
