// frontend-app/src/views/Playbook.vue
<template>
  <div class="playbook-page">
    <!-- 顶部操作栏 -->
    <div class="toolbar">
      <div>
        <el-button type="primary" :icon="Refresh" @click="loadList">刷新</el-button>
        <el-button v-if="isAdmin" :icon="Plus" @click="openCreate">新建剧本</el-button>
        <el-button v-if="isAdmin" :icon="Files" @click="seedTemplates">导入模板</el-button>
      </div>
      <div v-if="pendingApprovals.length > 0" class="pending-tip">
        <el-badge :value="pendingApprovals.length" type="danger">
          <el-button size="small" @click="openApprovals">待审批</el-button>
        </el-badge>
      </div>
    </div>

    <!-- 剧本列表 -->
    <el-card shadow="never" class="table-card">
      <el-table v-loading="loading" :data="list" stripe>
        <el-table-column prop="id" label="ID" width="70" />
        <el-table-column prop="name" label="名称" min-width="160" show-overflow-tooltip />
        <el-table-column prop="trigger" label="触发" width="110">
          <template #default="{ row }">
            <el-tag size="small" :type="triggerTag(row.trigger)">{{ row.trigger }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="description" label="描述" min-width="220" show-overflow-tooltip />
        <el-table-column label="步骤数" width="90" align="center">
          <template #default="{ row }">{{ row.steps?.length || 0 }}</template>
        </el-table-column>
        <el-table-column label="启用" width="90" align="center">
          <template #default="{ row }">
            <el-switch :model-value="row.enabled === 1" :disabled="!isAdmin" @change="(v: boolean) => toggle(row, v)" />
          </template>
        </el-table-column>
        <el-table-column label="操作" width="300" fixed="right">
          <template #default="{ row }">
            <el-button size="small" type="primary" plain @click="openDetail(row)">详情</el-button>
            <el-button size="small" type="success" plain @click="openExecute(row)">执行</el-button>
            <template v-if="isAdmin">
              <el-button size="small" plain @click="openEdit(row)">编辑</el-button>
              <el-popconfirm title="确认删除该剧本？" @confirm="remove(row)">
                <template #reference>
                  <el-button size="small" type="danger" plain>删除</el-button>
                </template>
              </el-popconfirm>
            </template>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 创建/编辑对话框 -->
    <el-dialog v-model="editVisible" :title="editing ? '编辑剧本' : '新建剧本'" width="680px">
      <el-form :model="form" label-width="90px">
        <el-form-item label="名称" required>
          <el-input v-model="form.name" placeholder="剧本名称" />
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="form.description" type="textarea" :rows="2" placeholder="剧本用途说明" />
        </el-form-item>
        <el-form-item label="触发">
          <el-select v-model="form.trigger" placeholder="触发方式">
            <el-option label="手动触发" value="manual" />
            <el-option label="暴力破解" value="brute_force" />
            <el-option label="情报命中" value="intel_match" />
            <el-option label="勒索告警" value="ransomware" />
          </el-select>
        </el-form-item>
        <el-form-item label="步骤 JSON">
          <el-input v-model="stepsJson" type="textarea" :rows="10" :placeholder="stepPlaceholder" />
          <div class="form-tip">{{ stepTip }}</div>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="editVisible = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="save">保存</el-button>
      </template>
    </el-dialog>

    <!-- 详情抽屉 -->
    <el-drawer v-model="detailVisible" :title="detail?.name" size="560px">
      <el-descriptions :column="1" border>
        <el-descriptions-item label="描述">{{ detail?.description || '-' }}</el-descriptions-item>
        <el-descriptions-item label="触发">{{ detail?.trigger }}</el-descriptions-item>
        <el-descriptions-item label="状态">
          <el-tag :type="detail?.enabled === 1 ? 'success' : 'info'">{{
            detail?.enabled === 1 ? '已启用' : '已停用'
          }}</el-tag>
        </el-descriptions-item>
      </el-descriptions>
      <h4>执行步骤</h4>
      <el-timeline v-if="detail?.steps?.length">
        <el-timeline-item v-for="(s, i) in detail.steps" :key="i" :type="stepType(s.type)" :hollow="true">
          <div class="step-item">
            <el-tag size="small" :type="stepType(s.type)">{{ stepLabel(s) }}</el-tag>
            <span class="step-name">{{ s.name || stepDesc(s) }}</span>
          </div>
        </el-timeline-item>
      </el-timeline>
      <el-empty v-else description="暂无步骤" :image-size="60" />
    </el-drawer>

    <!-- 执行对话框 -->
    <el-dialog v-model="execVisible" :title="`执行剧本：${execTarget?.name || ''}`" width="600px">
      <el-form label-width="90px">
        <el-form-item label="事件 JSON">
          <el-input
            v-model="eventJson"
            type="textarea"
            :rows="8"
            placeholder='{"ip":"185.220.101.34","severity":"high","confidence":0.9,"fail_count":8}'
          />
          <div class="form-tip">事件字段供 condition 判断与动作参数「字段名」引用。</div>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="execVisible = false">取消</el-button>
        <el-button type="primary" :loading="executing" @click="doExecute">执行</el-button>
      </template>
    </el-dialog>

    <!-- 执行结果 -->
    <el-dialog v-model="resultVisible" title="执行结果" width="640px">
      <el-alert
        v-if="runResult"
        :type="
          runResult.status === 'completed' ? 'success' : runResult.status === 'awaiting_approval' ? 'warning' : 'error'
        "
        :title="`状态：${runResult.status || 'unknown'}`"
        :description="runResult.success ? `运行ID: ${runResult.run_id}` : runResult.error"
        :closable="false"
        show-icon
        style="margin-bottom: 12px"
      />
      <el-table v-if="runResult?.results?.length" :data="runResult.results" size="small" border max-height="380">
        <el-table-column label="步骤" width="120">
          <template #default="{ row }">{{ row.name || row.type }}</template>
        </el-table-column>
        <el-table-column label="类型" width="110">
          <template #default="{ row }">
            <el-tag size="small" :type="stepType(row.type)">{{ row.type }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="结果" min-width="200">
          <template #default="{ row }">
            <span v-if="row.type === 'condition'">{{ row.ok ? '✅ 满足' : '⛔ 不满足' }}</span>
            <span v-else-if="row.success === false" class="err-text">{{ row.error || '失败' }}</span>
            <span v-else-if="row.status === 'pending'">等待人工审批（{{ row.approval_id }}）</span>
            <span v-else>{{ row.detail || row.message || '成功' }}</span>
          </template>
        </el-table-column>
      </el-table>
    </el-dialog>

    <!-- 待审批列表 -->
    <el-dialog v-model="approvalVisible" title="待人工审批" width="620px">
      <el-table :data="pendingApprovals" size="small" border>
        <el-table-column prop="id" label="审批ID" width="130" />
        <el-table-column prop="title" label="事项" min-width="200" />
        <el-table-column prop="playbookId" label="剧本ID" width="80" />
        <el-table-column label="操作" width="150">
          <template #default="{ row }">
            <el-button size="small" type="success" @click="handleApproval(row, 'approve')">批准</el-button>
            <el-button size="small" type="danger" @click="handleApproval(row, 'reject')">拒绝</el-button>
          </template>
        </el-table-column>
      </el-table>
      <el-empty v-if="pendingApprovals.length === 0" description="暂无待审批事项" :image-size="60" />
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { Refresh, Plus, Files } from '@element-plus/icons-vue';
import { playbookApi } from '@/api';
import { useUserStore } from '@/stores/user';
import type { Playbook, PlaybookStep, PlaybookRunResult } from '@/types';

const userStore = useUserStore();
const isAdmin = computed(() => userStore.user?.role_id === 1);

const list = ref<Playbook[]>([]);
const loading = ref(false);
const pendingApprovals = ref<Array<{ id: string; title: string; playbookId: number; status: string }>>([]);

const editVisible = ref(false);
const editing = ref<Playbook | null>(null);
const form = ref({ name: '', description: '', trigger: 'manual' });
const stepsJson = ref('[]');
const saving = ref(false);
// 占位提示（{{x}} 语法在模板中需经变量绑定，避免被解析为插值表达式）
const stepPlaceholder =
  '[{"type":"condition","fact":"fail_count","operator":"gt","value":5}, {"type":"action","action":"firewall_block","params":{"ip":"{{ip}}","duration":1800}}]';
const stepTip =
  '步骤类型：condition 条件 / action 动作(firewall_block,account_lock,raise_alert,notify,webhook,log_only) / approval 人工审批 / notification 通知 / wait 等待。动作参数支持 {{字段}} 引用执行事件字段。';

const detailVisible = ref(false);
const detail = ref<Playbook | null>(null);

const execVisible = ref(false);
const execTarget = ref<Playbook | null>(null);
const eventJson = ref('{}');
const executing = ref(false);

const resultVisible = ref(false);
const runResult = ref<PlaybookRunResult | null>(null);

const approvalVisible = ref(false);

async function loadList() {
  loading.value = true;
  try {
    const data = await playbookApi.list({ page: 1, pageSize: 100 });
    list.value = data.list ?? [];
  } catch (e) {
    ElMessage.error('加载剧本列表失败');
  } finally {
    loading.value = false;
  }
}

async function loadApprovals() {
  try {
    pendingApprovals.value = await playbookApi.pendingApprovals();
  } catch (e) {
    pendingApprovals.value = [];
  }
}

function triggerTag(trigger: string) {
  if (trigger === 'brute_force') return 'danger';
  if (trigger === 'intel_match') return 'warning';
  if (trigger === 'ransomware') return 'danger';
  return 'info';
}

function stepLabel(s: PlaybookStep) {
  const labels: Record<string, string> = {
    condition: '条件',
    action: '动作',
    approval: '审批',
    notification: '通知',
    wait: '等待'
  };
  return labels[s.type] || s.type;
}

function stepDesc(s: PlaybookStep) {
  if (s.type === 'condition') return `${s.fact} ${s.operator} ${JSON.stringify(s.value)}`;
  if (s.type === 'action') return `${s.action} ${JSON.stringify(s.params || {})}`;
  if (s.type === 'notification') return `通知（${s.channel || 'all'}）`;
  return '';
}

function stepType(type: string): 'primary' | 'success' | 'warning' | 'info' {
  if (type === 'action') return 'primary';
  if (type === 'approval') return 'warning';
  if (type === 'notification') return 'success';
  if (type === 'condition') return 'info';
  return 'info';
}

function openCreate() {
  editing.value = null;
  form.value = { name: '', description: '', trigger: 'manual' };
  stepsJson.value = JSON.stringify(
    [
      { type: 'condition', name: '条件示例', fact: 'severity', operator: 'eq', value: 'high' },
      { type: 'action', name: '封禁IP', action: 'firewall_block', params: { ip: '{{ip}}', duration: 3600 } }
    ],
    null,
    2
  );
  editVisible.value = true;
}

function openEdit(row: Playbook) {
  editing.value = row;
  form.value = { name: row.name, description: row.description || '', trigger: row.trigger || 'manual' };
  stepsJson.value = JSON.stringify(row.steps || [], null, 2);
  editVisible.value = true;
}

async function save() {
  if (!form.value.name) {
    ElMessage.warning('请输入剧本名称');
    return;
  }
  let steps: PlaybookStep[];
  try {
    steps = JSON.parse(stepsJson.value);
  } catch (e) {
    ElMessage.error('步骤 JSON 格式错误');
    return;
  }
  saving.value = true;
  try {
    if (editing.value) {
      await playbookApi.update(editing.value.id, { ...form.value, steps });
      ElMessage.success('剧本已更新');
    } else {
      await playbookApi.create({ ...form.value, steps });
      ElMessage.success('剧本创建成功');
    }
    editVisible.value = false;
    loadList();
  } catch (e) {
    ElMessage.error('保存失败');
  } finally {
    saving.value = false;
  }
}

async function toggle(row: Playbook, enabled: boolean) {
  try {
    await playbookApi.update(row.id, { enabled: enabled ? 1 : 0 });
    row.enabled = enabled ? 1 : 0;
    ElMessage.success(enabled ? '已启用' : '已停用');
  } catch (e) {
    ElMessage.error('操作失败');
  }
}

async function remove(row: Playbook) {
  try {
    await playbookApi.remove(row.id);
    ElMessage.success('剧本已删除');
    loadList();
  } catch (e) {
    ElMessage.error('删除失败');
  }
}

async function seedTemplates() {
  try {
    const r = await playbookApi.seedTemplates();
    ElMessage.success(`模板导入完成（新增 ${r.seeded} 个）`);
    loadList();
  } catch (e) {
    ElMessage.error('模板导入失败');
  }
}

async function openDetail(row: Playbook) {
  detail.value = row;
  detailVisible.value = true;
}

function openExecute(row: Playbook) {
  execTarget.value = row;
  eventJson.value = JSON.stringify({ ip: '185.220.101.34', severity: 'high', confidence: 0.9, fail_count: 8 }, null, 2);
  execVisible.value = true;
}

async function doExecute() {
  let event: Record<string, unknown>;
  try {
    event = JSON.parse(eventJson.value);
  } catch (e) {
    ElMessage.error('事件 JSON 格式错误');
    return;
  }
  executing.value = true;
  try {
    const r = await playbookApi.execute(execTarget.value!.id, event);
    runResult.value = r;
    execVisible.value = false;
    resultVisible.value = true;
    loadApprovals();
    loadList();
  } catch (e) {
    ElMessage.error('执行失败');
  } finally {
    executing.value = false;
  }
}

function openApprovals() {
  approvalVisible.value = true;
  loadApprovals();
}

async function handleApproval(row: { id: string }, decision: 'approve' | 'reject') {
  try {
    await playbookApi.confirmApproval(row.id, decision);
    ElMessage.success(decision === 'approve' ? '已批准' : '已拒绝');
    loadApprovals();
  } catch (e) {
    ElMessage.error('处理失败');
  }
}

onMounted(() => {
  loadList();
  loadApprovals();
});
</script>

<style scoped>
.playbook-page {
  padding: 4px;
}
.toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}
.table-card {
  border-radius: 8px;
}
.form-tip {
  font-size: 12px;
  color: #909399;
  margin-top: 6px;
  line-height: 1.6;
}
.step-item {
  display: flex;
  align-items: center;
  gap: 8px;
}
.step-name {
  color: #606266;
}
.err-text {
  color: #f56c6c;
}
</style>

// frontend-react/src/pages/Playbook.tsx
import { useEffect, useMemo, useState } from 'react';
import { playbookApi } from '@/api';
import type { Playbook, PlaybookApproval, PlaybookRunResult, PlaybookStep, PlaybookStepResult } from '@/api';
import Badge from '@/components/ui/badge';
import Button from '@/components/ui/button';
import Dialog from '@/components/ui/dialog';
import { Table } from '@/components/ui/table';
import { useToast } from '@/components/ui/use-toast';
import { useUserStore } from '@/stores/user';

const PAGE_SIZE = 10;

const fieldCls =
  'rounded-md border border-cyan-500/20 bg-[#1a2340] px-3 py-2 text-sm text-gray-300 outline-none transition-colors placeholder:text-gray-500 focus:border-cyan-500/60';

const TRIGGERS: Array<{ value: string; label: string }> = [
  { value: 'manual', label: '手动触发' },
  { value: 'brute_force', label: '暴力破解' },
  { value: 'intel_match', label: '情报命中' },
  { value: 'ransomware', label: '勒索告警' }
];

const STEP_PLACEHOLDER =
  '[{"type":"condition","fact":"fail_count","operator":"gt","value":5}, {"type":"action","action":"firewall_block","params":{"ip":"{{ip}}","duration":1800}}]';

const STEP_TIP =
  '步骤类型：condition 条件 / action 动作(firewall_block,account_lock,raise_alert,notify,webhook,log_only) / approval 人工审批 / notification 通知 / wait 等待。动作参数支持 {{字段}} 引用执行事件字段。';

function isEnabled(v: number | boolean | undefined): boolean {
  return v !== 0 && v !== false && v !== undefined;
}

function triggerVariant(trigger?: string): 'default' | 'success' | 'warning' | 'danger' {
  if (trigger === 'brute_force' || trigger === 'ransomware') return 'danger';
  if (trigger === 'intel_match') return 'warning';
  return 'default';
}

function triggerLabel(trigger?: string): string {
  return TRIGGERS.find((t) => t.value === trigger)?.label || trigger || '-';
}

function formatTime(t?: string): string {
  return t ? new Date(t).toLocaleString('zh-CN') : '-';
}

function stepTypeLabel(type?: string): string {
  const labels: Record<string, string> = {
    condition: '条件',
    action: '动作',
    approval: '审批',
    notification: '通知',
    wait: '等待'
  };
  return (type && labels[type]) || type || '-';
}

function resultCell(r: PlaybookStepResult): string {
  if (r.type === 'condition') return r.ok ? '✅ 满足' : '⛔ 不满足';
  if (r.success === false) return r.error || '失败';
  if (r.status === 'pending') return `等待人工审批（${r.approval_id}）`;
  return r.detail || r.message || '成功';
}

function resultStatusVariant(status?: string): 'success' | 'warning' | 'error' {
  if (status === 'completed') return 'success';
  if (status === 'awaiting_approval') return 'warning';
  return 'error';
}

function ToggleSwitch({
  checked,
  disabled,
  onChange
}: {
  checked: boolean;
  disabled?: boolean;
  onChange: (v: boolean) => void;
}) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      disabled={disabled}
      onClick={() => onChange(!checked)}
      className={`relative inline-flex h-5 w-9 shrink-0 items-center rounded-full transition-colors disabled:cursor-not-allowed disabled:opacity-40 ${
        checked ? 'bg-green-500' : 'bg-gray-600'
      }`}
    >
      <span
        className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
          checked ? 'translate-x-[18px]' : 'translate-x-0.5'
        }`}
      />
    </button>
  );
}

function Pagination({
  page,
  total,
  pageSize,
  onChange
}: {
  page: number;
  total: number;
  pageSize: number;
  onChange: (p: number) => void;
}) {
  const pages = Math.max(1, Math.ceil(total / pageSize));
  if (pages <= 1) return null;
  return (
    <div className="mt-4 flex items-center justify-end gap-2 text-xs text-gray-400">
      <span>共 {total} 条</span>
      <button
        type="button"
        disabled={page <= 1}
        onClick={() => onChange(page - 1)}
        className="rounded border border-white/10 px-2 py-1 transition-colors hover:border-cyan-500/40 disabled:opacity-40"
      >
        上一页
      </button>
      <span className="px-1">
        {page} / {pages}
      </span>
      <button
        type="button"
        disabled={page >= pages}
        onClick={() => onChange(page + 1)}
        className="rounded border border-white/10 px-2 py-1 transition-colors hover:border-cyan-500/40 disabled:opacity-40"
      >
        下一页
      </button>
    </div>
  );
}

interface PlaybookForm {
  name: string;
  description: string;
  trigger: string;
  enabled: boolean;
  stepsJson: string;
}

const DEFAULT_STEPS: PlaybookStep[] = [
  { type: 'condition', name: '条件示例', fact: 'severity', operator: 'eq', value: 'high' },
  { type: 'action', name: '封禁IP', action: 'firewall_block', params: { ip: '{{ip}}', duration: 3600 } }
];

const EMPTY_FORM: PlaybookForm = {
  name: '',
  description: '',
  trigger: 'manual',
  enabled: true,
  stepsJson: JSON.stringify(DEFAULT_STEPS, null, 2)
};

export default function Playbook() {
  const { toast } = useToast();
  const user = useUserStore((s) => s.user);
  const isAdmin = user?.role_id === 1;

  const [list, setList] = useState<Playbook[]>([]);
  const [loading, setLoading] = useState(false);
  const [pendingApprovals, setPendingApprovals] = useState<PlaybookApproval[]>([]);
  const [page, setPage] = useState(1);

  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form, setForm] = useState<PlaybookForm>(EMPTY_FORM);
  const [saving, setSaving] = useState(false);

  const [execVisible, setExecVisible] = useState(false);
  const [execTarget, setExecTarget] = useState<Playbook | null>(null);
  const [eventJson, setEventJson] = useState('{}');
  const [executing, setExecuting] = useState(false);

  const [resultVisible, setResultVisible] = useState(false);
  const [runResult, setRunResult] = useState<PlaybookRunResult | null>(null);

  const [deleteTarget, setDeleteTarget] = useState<Playbook | null>(null);
  const [deleting, setDeleting] = useState(false);

  const [approvalVisible, setApprovalVisible] = useState(false);

  async function loadList() {
    setLoading(true);
    try {
      const data = await playbookApi.list({ page: 1, pageSize: 200 });
      setList(data?.list ?? []);
    } catch {
      setList([]);
    }
    setLoading(false);
  }

  async function loadApprovals() {
    try {
      setPendingApprovals(await playbookApi.pendingApprovals());
    } catch {
      setPendingApprovals([]);
    }
  }

  useEffect(() => {
    loadList();
    loadApprovals();
  }, []);

  const paginated = useMemo(() => {
    const s = (page - 1) * PAGE_SIZE;
    return list.slice(s, s + PAGE_SIZE);
  }, [list, page]);

  function openCreate() {
    setEditingId(null);
    setForm({ ...EMPTY_FORM });
    setDialogOpen(true);
  }

  function openEdit(p: Playbook) {
    setEditingId(p.id);
    setForm({
      name: p.name,
      description: p.description || '',
      trigger: p.trigger || 'manual',
      enabled: isEnabled(p.enabled),
      stepsJson: JSON.stringify(Array.isArray(p.steps) ? p.steps : [], null, 2)
    });
    setDialogOpen(true);
  }

  async function save() {
    if (!form.name.trim()) {
      toast({ title: '请输入剧本名称', variant: 'warning' });
      return;
    }
    let steps: PlaybookStep[];
    try {
      const parsed: unknown = JSON.parse(form.stepsJson || '[]');
      if (!Array.isArray(parsed)) throw new Error('steps must be array');
      steps = parsed as PlaybookStep[];
    } catch {
      toast({ title: '步骤 JSON 格式错误，请检查', variant: 'error' });
      return;
    }
    const payload = {
      name: form.name.trim(),
      description: form.description.trim() || undefined,
      trigger: form.trigger,
      enabled: form.enabled,
      steps
    };
    setSaving(true);
    try {
      if (editingId !== null) {
        await playbookApi.update(editingId, payload);
        toast({ title: '剧本已更新', variant: 'success' });
      } else {
        await playbookApi.create(payload);
        toast({ title: '剧本创建成功', variant: 'success' });
      }
      setDialogOpen(false);
      loadList();
    } catch {
      // http 拦截器已提示
    }
    setSaving(false);
  }

  async function toggleEnabled(p: Playbook) {
    const enabled = !isEnabled(p.enabled);
    try {
      await playbookApi.update(p.id, { enabled });
      toast({ title: `剧本已${enabled ? '启用' : '停用'}`, variant: 'success' });
      loadList();
    } catch {
      // http 拦截器已提示
    }
  }

  async function confirmDelete() {
    if (!deleteTarget) return;
    setDeleting(true);
    try {
      await playbookApi.remove(deleteTarget.id);
      toast({ title: '剧本已删除', variant: 'success' });
      setDeleteTarget(null);
      loadList();
    } catch {
      // http 拦截器已提示
    }
    setDeleting(false);
  }

  async function seedTemplates() {
    try {
      const r = await playbookApi.seedTemplates();
      toast({ title: `模板导入完成（新增 ${r.seeded} 个）`, variant: 'success' });
      loadList();
    } catch {
      // http 拦截器已提示
    }
  }

  function openExecute(p: Playbook) {
    setExecTarget(p);
    setEventJson(JSON.stringify({ ip: '185.220.101.34', severity: 'high', confidence: 0.9, fail_count: 8 }, null, 2));
    setExecVisible(true);
  }

  async function doExecute() {
    if (!execTarget) return;
    let event: Record<string, unknown>;
    try {
      const parsed: unknown = JSON.parse(eventJson || '{}');
      if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) throw new Error('bad event');
      event = parsed as Record<string, unknown>;
    } catch {
      toast({ title: '事件 JSON 格式错误', variant: 'error' });
      return;
    }
    setExecuting(true);
    try {
      const r = await playbookApi.execute(execTarget.id, event);
      setRunResult(r);
      setExecVisible(false);
      setResultVisible(true);
      loadApprovals();
      loadList();
    } catch {
      // http 拦截器已提示
    }
    setExecuting(false);
  }

  function openApprovals() {
    setApprovalVisible(true);
    loadApprovals();
  }

  async function handleApproval(a: PlaybookApproval, decision: 'approve' | 'reject') {
    try {
      await playbookApi.confirmApproval(a.id, decision);
      toast({ title: decision === 'approve' ? '已批准' : '已拒绝', variant: 'success' });
      loadApprovals();
    } catch {
      // http 拦截器已提示
    }
  }

  return (
    <div className="space-y-5">
      {/* 页头 */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-white">SOAR 编排</h2>
          <p className="mt-1 text-sm text-gray-400">安全剧本自动化编排与人工审批</p>
        </div>
        <div className="flex items-center gap-2">
          <Button size="sm" variant="outline" onClick={loadList}>
            刷新
          </Button>
          {isAdmin && (
            <Button size="sm" variant="outline" onClick={seedTemplates}>
              导入模板
            </Button>
          )}
          {isAdmin && (
            <Button size="sm" onClick={openCreate}>
              新建剧本
            </Button>
          )}
          {pendingApprovals.length > 0 && (
            <Button size="sm" variant="outline" onClick={openApprovals} className="relative">
              待审批
              <span className="absolute -right-1 -top-1 flex h-4 min-w-4 items-center justify-center rounded-full bg-red-500 px-1 text-[10px] font-medium text-white">
                {pendingApprovals.length}
              </span>
            </Button>
          )}
        </div>
      </div>

      {/* 剧本列表 */}
      <div className="rounded-lg border border-cyan-500/20 bg-[#16213e]/80 p-5">
        <Table>
          <thead>
            <tr className="border-b border-cyan-500/20 text-left text-xs text-cyan-200/70">
              <th className="px-2 py-2 font-medium">ID</th>
              <th className="px-2 py-2 font-medium">名称</th>
              <th className="px-2 py-2 font-medium">触发</th>
              <th className="px-2 py-2 font-medium">描述</th>
              <th className="px-2 py-2 font-medium">步骤数</th>
              <th className="px-2 py-2 font-medium">启用</th>
              <th className="px-2 py-2 font-medium">创建人</th>
              <th className="px-2 py-2 font-medium">更新时间</th>
              <th className="px-2 py-2 font-medium">操作</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-white/5">
            {paginated.map((p) => {
              const enabled = isEnabled(p.enabled);
              return (
                <tr key={p.id} className="hover:bg-white/5">
                  <td className="px-2 py-2 font-mono text-xs text-gray-400">{p.id}</td>
                  <td className="px-2 py-2 text-gray-300">{p.name}</td>
                  <td className="px-2 py-2">
                    <Badge variant={triggerVariant(p.trigger)}>{triggerLabel(p.trigger)}</Badge>
                  </td>
                  <td className="max-w-[220px] truncate px-2 py-2 text-gray-400" title={p.description || ''}>
                    {p.description || '-'}
                  </td>
                  <td className="px-2 py-2 text-gray-400">{Array.isArray(p.steps) ? p.steps.length : 0}</td>
                  <td className="px-2 py-2">
                    <div className="flex items-center gap-2">
                      <ToggleSwitch checked={enabled} disabled={!isAdmin} onChange={() => toggleEnabled(p)} />
                      <Badge variant={enabled ? 'success' : 'default'}>{enabled ? '启用' : '停用'}</Badge>
                    </div>
                  </td>
                  <td className="px-2 py-2 text-gray-400">{p.created_by ?? '-'}</td>
                  <td className="px-2 py-2 text-gray-400">{formatTime(p.updated_at)}</td>
                  <td className="px-2 py-2">
                    <div className="flex gap-3">
                      <button
                        type="button"
                        onClick={() => openExecute(p)}
                        className="text-xs text-green-400 transition-colors hover:text-green-300"
                      >
                        执行
                      </button>
                      {isAdmin && (
                        <>
                          <button
                            type="button"
                            onClick={() => openEdit(p)}
                            className="text-xs text-cyan-400 transition-colors hover:text-cyan-300"
                          >
                            编辑
                          </button>
                          <button
                            type="button"
                            onClick={() => setDeleteTarget(p)}
                            className="text-xs text-red-400 transition-colors hover:text-red-300"
                          >
                            删除
                          </button>
                        </>
                      )}
                    </div>
                  </td>
                </tr>
              );
            })}
            {paginated.length === 0 && (
              <tr>
                <td colSpan={9} className="px-2 py-6 text-center text-gray-500">
                  {loading ? '加载中…' : '暂无剧本'}
                </td>
              </tr>
            )}
          </tbody>
        </Table>
        <Pagination page={page} total={list.length} pageSize={PAGE_SIZE} onChange={setPage} />
      </div>

      {/* 新建/编辑弹窗 */}
      <Dialog
        open={dialogOpen}
        onOpenChange={(open) => !open && setDialogOpen(false)}
        title={editingId !== null ? '编辑剧本' : '新建剧本'}
        footer={
          <>
            <Button size="sm" variant="outline" onClick={() => setDialogOpen(false)}>
              取消
            </Button>
            <Button size="sm" disabled={saving} onClick={save}>
              {saving ? '保存中…' : '保存'}
            </Button>
          </>
        }
      >
        <div className="max-h-[60vh] space-y-4 overflow-y-auto pr-1">
          <div>
            <label className="mb-1 block text-xs text-gray-400">名称</label>
            <input
              className={`${fieldCls} w-full`}
              value={form.name}
              placeholder="剧本名称"
              onChange={(e) => setForm({ ...form, name: e.target.value })}
            />
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-400">描述</label>
            <textarea
              className={`${fieldCls} w-full resize-none`}
              rows={2}
              value={form.description}
              placeholder="剧本用途说明"
              onChange={(e) => setForm({ ...form, description: e.target.value })}
            />
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-400">触发方式</label>
            <select
              className={`${fieldCls} w-full`}
              value={form.trigger}
              onChange={(e) => setForm({ ...form, trigger: e.target.value })}
            >
              {TRIGGERS.map((t) => (
                <option key={t.value} value={t.value}>
                  {t.label}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-400">步骤 JSON（数组，五项步骤类型）</label>
            <textarea
              className={`${fieldCls} w-full resize-none font-mono text-xs`}
              rows={10}
              value={form.stepsJson}
              placeholder={STEP_PLACEHOLDER}
              onChange={(e) => setForm({ ...form, stepsJson: e.target.value })}
            />
            <div className="mt-1 text-xs leading-5 text-gray-500">{STEP_TIP}</div>
          </div>
          <label className="flex cursor-pointer items-center gap-2 text-sm text-gray-300">
            <input
              type="checkbox"
              checked={form.enabled}
              onChange={(e) => setForm({ ...form, enabled: e.target.checked })}
              className="h-4 w-4 accent-cyan-500"
            />
            创建后立即启用
          </label>
        </div>
      </Dialog>

      {/* 执行弹窗 */}
      <Dialog
        open={execVisible}
        onOpenChange={(open) => !open && setExecVisible(false)}
        title={`执行剧本：${execTarget?.name || ''}`}
        footer={
          <>
            <Button size="sm" variant="outline" onClick={() => setExecVisible(false)}>
              取消
            </Button>
            <Button size="sm" disabled={executing} onClick={doExecute}>
              {executing ? '执行中…' : '执行'}
            </Button>
          </>
        }
      >
        <div className="space-y-2">
          <label className="block text-xs text-gray-400">事件 JSON（可选）</label>
          <textarea
            className={`${fieldCls} w-full resize-none font-mono text-xs`}
            rows={8}
            value={eventJson}
            placeholder='{"ip":"185.220.101.34","severity":"high","confidence":0.9,"fail_count":8}'
            onChange={(e) => setEventJson(e.target.value)}
          />
          <div className="text-xs leading-5 text-gray-500">
            事件字段供 condition 判断与动作参数「{'{{字段}}'}」引用。
          </div>
        </div>
      </Dialog>

      {/* 执行结果弹窗 */}
      <Dialog open={resultVisible} onOpenChange={(open) => !open && setResultVisible(false)} title="执行结果">
        <div className="space-y-3">
          <div
            className={`rounded-md border px-3 py-2 text-sm ${
              resultStatusVariant(runResult?.status) === 'success'
                ? 'border-green-500/30 bg-green-500/10 text-green-300'
                : resultStatusVariant(runResult?.status) === 'warning'
                  ? 'border-amber-500/30 bg-amber-500/10 text-amber-300'
                  : 'border-red-500/30 bg-red-500/10 text-red-300'
            }`}
          >
            <div className="font-medium">状态：{runResult?.status || 'unknown'}</div>
            <div className="mt-0.5 text-xs opacity-80">
              {runResult?.success ? `运行ID: ${runResult.run_id}` : runResult?.error || '运行失败'}
            </div>
          </div>
          {Array.isArray(runResult?.results) && runResult!.results!.length > 0 && (
            <Table>
              <thead>
                <tr className="border-b border-cyan-500/20 text-left text-xs text-cyan-200/70">
                  <th className="px-2 py-2 font-medium">步骤</th>
                  <th className="px-2 py-2 font-medium">类型</th>
                  <th className="px-2 py-2 font-medium">结果</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {runResult!.results!.map((r, i) => (
                  <tr key={i} className="hover:bg-white/5">
                    <td className="px-2 py-2 text-gray-300">{r.name || stepTypeLabel(r.type)}</td>
                    <td className="px-2 py-2">
                      <Badge variant={r.type === 'action' ? 'default' : r.type === 'approval' ? 'warning' : 'default'}>
                        {stepTypeLabel(r.type)}
                      </Badge>
                    </td>
                    <td className="px-2 py-2 text-gray-400">{resultCell(r)}</td>
                  </tr>
                ))}
              </tbody>
            </Table>
          )}
        </div>
      </Dialog>

      {/* 删除确认 */}
      <Dialog open={!!deleteTarget} onOpenChange={(open) => !open && setDeleteTarget(null)} title="删除确认">
        <p className="text-sm text-gray-600">确定要删除剧本「{deleteTarget?.name}」吗？删除后无法恢复。</p>
        <div className="mt-4 flex justify-end gap-2">
          <Button size="sm" variant="outline" onClick={() => setDeleteTarget(null)}>
            取消
          </Button>
          <Button size="sm" variant="destructive" disabled={deleting} onClick={confirmDelete}>
            {deleting ? '删除中…' : '删除'}
          </Button>
        </div>
      </Dialog>

      {/* 待审批 */}
      <Dialog open={approvalVisible} onOpenChange={(open) => !open && setApprovalVisible(false)} title="待人工审批">
        {pendingApprovals.length === 0 ? (
          <div className="py-8 text-center text-sm text-gray-500">暂无待审批事项</div>
        ) : (
          <Table>
            <thead>
              <tr className="border-b border-cyan-500/20 text-left text-xs text-cyan-200/70">
                <th className="px-2 py-2 font-medium">审批ID</th>
                <th className="px-2 py-2 font-medium">事项</th>
                <th className="px-2 py-2 font-medium">剧本ID</th>
                <th className="px-2 py-2 font-medium">操作</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {pendingApprovals.map((a) => (
                <tr key={a.id} className="hover:bg-white/5">
                  <td className="px-2 py-2 font-mono text-xs text-gray-400">{a.id}</td>
                  <td className="px-2 py-2 text-gray-300">{a.title}</td>
                  <td className="px-2 py-2 text-gray-400">{a.playbookId}</td>
                  <td className="px-2 py-2">
                    <div className="flex gap-2">
                      <Button size="sm" onClick={() => handleApproval(a, 'approve')}>
                        批准
                      </Button>
                      <Button size="sm" variant="destructive" onClick={() => handleApproval(a, 'reject')}>
                        拒绝
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        )}
      </Dialog>
    </div>
  );
}
