// frontend-app/src/views/Reports.vue
<template>
  <div class="page-container">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px">
      <h2 style="color: #00d4ff; margin: 0">报告管理</h2>
      <div>
        <el-dropdown style="margin-right: 8px" @command="downloadCsv">
          <el-button type="warning" :icon="Download">批量导出 CSV</el-button>
          <template #dropdown>
            <el-dropdown-menu>
              <el-dropdown-item command="alerts">安全告警</el-dropdown-item>
              <el-dropdown-item command="scan">扫描结果</el-dropdown-item>
              <el-dropdown-item command="baseline">基线检查</el-dropdown-item>
              <el-dropdown-item command="reports">报告列表</el-dropdown-item>
            </el-dropdown-menu>
          </template>
        </el-dropdown>
        <el-button
          type="primary"
          :icon="RefreshRight"
          @click="
            loadReports();
            loadReportStats();
          "
          >刷新</el-button
        >
      </div>
    </div>

    <el-row :gutter="20" style="margin-bottom: 20px">
      <el-col :span="6">
        <el-card shadow="hover" style="background: rgba(26, 26, 46, 0.6); border-color: #333">
          <div style="text-align: center">
            <div style="font-size: 32px; color: #00d4ff; font-weight: bold">{{ reportStats.total || 0 }}</div>
            <div style="font-size: 14px; color: #999; margin-top: 5px">总报告数</div>
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="hover" style="background: rgba(26, 26, 46, 0.6); border-color: #333">
          <div style="text-align: center">
            <div style="font-size: 32px; color: #e74c3c; font-weight: bold">{{ reportStats.djpp || 0 }}</div>
            <div style="font-size: 14px; color: #999; margin-top: 5px">等保测评报告</div>
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="hover" style="background: rgba(26, 26, 46, 0.6); border-color: #333">
          <div style="text-align: center">
            <div style="font-size: 32px; color: #27ae60; font-weight: bold">{{ reportStats.virus || 0 }}</div>
            <div style="font-size: 14px; color: #999; margin-top: 5px">病毒查杀报告</div>
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="hover" style="background: rgba(26, 26, 46, 0.6); border-color: #333">
          <div style="text-align: center">
            <div style="font-size: 32px; color: #f39c12; font-weight: bold">{{ reportStats.baseline || 0 }}</div>
            <div style="font-size: 14px; color: #999; margin-top: 5px">基线检查报告</div>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <el-tabs v-model="activeTab" style="margin-bottom: 20px">
      <el-tab-pane label="全部报告" name="all">
        <el-table
          v-loading="loading"
          :data="reports"
          stripe
          style="width: 100%"
          :header-cell-style="{ background: '#1a1a3e', color: '#00d4ff' }"
          :row-style="{ background: 'rgba(26,26,46,0.6)' }"
        >
          <el-table-column prop="id" label="ID" width="80" />
          <el-table-column prop="title" label="报告标题" min-width="250" />
          <el-table-column prop="typeLabel" label="类型" width="120">
            <template #default="{ row }">
              <el-tag
                :type="
                  row.type === 'djpp'
                    ? 'danger'
                    : row.type === 'virus'
                      ? 'success'
                      : row.type === 'baseline'
                        ? 'warning'
                        : 'info'
                "
                size="small"
                >{{ row.typeLabel }}</el-tag
              >
            </template>
          </el-table-column>
          <el-table-column prop="generatedBy" label="生成者" width="120" />
          <el-table-column prop="generatedAt" label="生成时间" width="180" />
          <el-table-column label="操作" width="300" fixed="right">
            <template #default="{ row }">
              <el-button type="primary" link size="small" @click="viewReport(row)">查看</el-button>
              <el-button type="success" link size="small" @click="downloadMarkdownReport(row)">下载MD</el-button>
              <el-button type="warning" link size="small" :loading="generatingPDF" @click="generateAndDownloadDOCX(row)"
                >下载DOCX</el-button
              >
              <el-button type="danger" link size="small" @click="deleteReport(row)">删除</el-button>
            </template>
          </el-table-column>
        </el-table>
      </el-tab-pane>

      <el-tab-pane label="等保测评报告" name="djpp">
        <el-table
          v-loading="loading"
          :data="reports.filter((r) => r.type === 'djpp')"
          stripe
          style="width: 100%"
          :header-cell-style="{ background: '#1a1a3e', color: '#00d4ff' }"
          :row-style="{ background: 'rgba(26,26,46,0.6)' }"
        >
          <el-table-column prop="id" label="ID" width="80" />
          <el-table-column prop="title" label="报告标题" min-width="250" />
          <el-table-column prop="generatedBy" label="生成者" width="120" />
          <el-table-column prop="generatedAt" label="生成时间" width="180" />
          <el-table-column label="操作" width="300" fixed="right">
            <template #default="{ row }">
              <el-button type="primary" link size="small" @click="viewReport(row)">查看</el-button>
              <el-button type="success" link size="small" @click="downloadMarkdownReport(row)">下载MD</el-button>
              <el-button type="warning" link size="small" :loading="generatingPDF" @click="generateAndDownloadDOCX(row)"
                >下载DOCX</el-button
              >
              <el-button type="danger" link size="small" @click="deleteReport(row)">删除</el-button>
            </template>
          </el-table-column>
        </el-table>
      </el-tab-pane>

      <el-tab-pane label="病毒查杀报告" name="virus">
        <el-table
          v-loading="loading"
          :data="reports.filter((r) => r.type === 'virus')"
          stripe
          style="width: 100%"
          :header-cell-style="{ background: '#1a1a3e', color: '#00d4ff' }"
          :row-style="{ background: 'rgba(26,26,46,0.6)' }"
        >
          <el-table-column prop="id" label="ID" width="80" />
          <el-table-column prop="title" label="报告标题" min-width="250" />
          <el-table-column prop="generatedBy" label="生成者" width="120" />
          <el-table-column prop="generatedAt" label="生成时间" width="180" />
          <el-table-column label="操作" width="300" fixed="right">
            <template #default="{ row }">
              <el-button type="primary" link size="small" @click="viewReport(row)">查看</el-button>
              <el-button type="success" link size="small" @click="downloadMarkdownReport(row)">下载MD</el-button>
              <el-button type="warning" link size="small" :loading="generatingPDF" @click="generateAndDownloadDOCX(row)"
                >下载DOCX</el-button
              >
              <el-button type="danger" link size="small" @click="deleteReport(row)">删除</el-button>
            </template>
          </el-table-column>
        </el-table>
      </el-tab-pane>

      <el-tab-pane label="基线检查报告" name="baseline">
        <el-table
          v-loading="loading"
          :data="reports.filter((r) => r.type === 'baseline')"
          stripe
          style="width: 100%"
          :header-cell-style="{ background: '#1a1a3e', color: '#00d4ff' }"
          :row-style="{ background: 'rgba(26,26,46,0.6)' }"
        >
          <el-table-column prop="id" label="ID" width="80" />
          <el-table-column prop="title" label="报告标题" min-width="250" />
          <el-table-column prop="generatedBy" label="生成者" width="120" />
          <el-table-column prop="generatedAt" label="生成时间" width="180" />
          <el-table-column label="操作" width="300" fixed="right">
            <template #default="{ row }">
              <el-button type="primary" link size="small" @click="viewReport(row)">查看</el-button>
              <el-button type="success" link size="small" @click="downloadMarkdownReport(row)">下载MD</el-button>
              <el-button type="warning" link size="small" :loading="generatingPDF" @click="generateAndDownloadDOCX(row)"
                >下载DOCX</el-button
              >
              <el-button type="danger" link size="small" @click="deleteReport(row)">删除</el-button>
            </template>
          </el-table-column>
        </el-table>
      </el-tab-pane>
    </el-tabs>

    <el-drawer
      v-model="showDetail"
      :title="reportDetail?.title || '报告详情'"
      size="60%"
      :style="{ background: '#1a1a2e' }"
    >
      <div v-if="reportDetail" style="color: #e0e0e0; line-height: 1.8">
        <p><strong>类型：</strong>{{ reportDetail.typeLabel }}</p>
        <p><strong>生成者：</strong>{{ reportDetail.generatedBy }}</p>
        <p><strong>时间：</strong>{{ reportDetail.generatedAt }}</p>
        <el-divider />
        <div style="white-space: pre-wrap; max-height: 60vh; overflow-y: auto">
          {{ reportDetail.content || reportDetail.stats ? JSON.stringify(reportDetail.stats) : '暂无内容' }}
        </div>
      </div>
    </el-drawer>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { RefreshRight, Download } from '@element-plus/icons-vue';
import { useUserStore } from '@/stores/user';
import { legacyApi } from '@/api';

// 与旧版 index.html 保持一致，用于拼接 DOCX 下载地址
const API_BASE = 'http://localhost:3000/api';

const loading = ref(true);
const reports = ref<Array<Record<string, any>>>([]);
const reportDetail = ref<Record<string, any> | null>(null);
const showDetail = ref(false);
const activeTab = ref('all');
const reportStats = ref<Record<string, any>>({ total: 0, djpp: 0, virus: 0, baseline: 0, scan: 0 });
const generatingPDF = ref(false);

const userStore = useUserStore();
const CSV_TYPES: Record<string, string> = {
  alerts: '告警',
  scan: '扫描',
  baseline: '基线',
  reports: '报告'
};

/** 批量导出 CSV（带鉴权头的流式下载） */
async function downloadCsv(type: string) {
  try {
    const resp = await fetch(`${API_BASE}/reports/export/csv?type=${type}`, {
      headers: { Authorization: `Bearer ${userStore.token}` }
    });
    if (!resp.ok) {
      ElMessage.error('CSV 导出失败');
      return;
    }
    const blob = await resp.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${type}_export_${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    ElMessage.success(`${CSV_TYPES[type] || type}数据已导出`);
  } catch (e) {
    ElMessage.error('CSV 导出失败: ' + (e as Error).message);
  }
}

async function loadReportStats() {
  try {
    const res = await legacyApi.get('/reports/stats');
    if (res && res.code === 0) {
      reportStats.value = res.data as Record<string, any>;
    }
  } catch (e) {
    console.error('获取报告统计失败:', e);
  }
}

async function loadReports() {
  loading.value = true;
  try {
    let url = '/reports/list?page=1&pageSize=100';
    if (activeTab.value !== 'all') {
      url += `&type=${activeTab.value}`;
    }
    const res = await legacyApi.get(url);
    if (res && res.code === 0) {
      const data = res.data as any;
      reports.value = ((data && data.reports) || []).map((r: any) => ({
        id: r.id,
        reportId: r.reportId,
        title: r.title || '未命名报告',
        type: r.type,
        typeLabel: r.typeLabel || r.type,
        content: r.content || (typeof r.content === 'string' ? r.content : ''),
        generatedBy: r.generatedBy || '-',
        generatedAt: r.generatedAt ? new Date(r.generatedAt).toLocaleString('zh-CN') : '-',
        stats: r.stats || null,
        hasPDF: r.hasPDF || false,
        pdfUrl: r.pdfUrl || null
      }));
    }
  } catch (e) {
    console.error('获取报告列表失败:', e);
    ElMessage.error('获取报告列表失败');
    reports.value = [];
  }
  loading.value = false;
}

function viewReport(report: Record<string, any>) {
  reportDetail.value = report;
  showDetail.value = true;
}

function downloadMarkdownReport(report: Record<string, any>) {
  const content = report.content || '无内容';
  const blob = new Blob(
    [`# ${report.title}\n\n生成时间: ${report.generatedAt}\n生成者: ${report.generatedBy}\n\n${content}`],
    { type: 'text/markdown;charset=utf-8' }
  );
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = report.title + '.md';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  ElMessage.success('Markdown报告已下载');
}

async function generateAndDownloadDOCX(report: Record<string, any>) {
  try {
    generatingPDF.value = true;
    ElMessage.info('正在生成DOCX报告，请稍候...');

    const res = await legacyApi.post(`/reports/${report.id}/generate-docx`, {});
    if (res && res.code === 0) {
      const data = res.data as any;
      const docxUrl = data.downloadUrl;
      const fullUrl = `${API_BASE}${docxUrl}`;

      window.open(fullUrl, '_blank');
      ElMessage.success('DOCX报告已下载');
      report.hasDOCX = true;
    } else {
      ElMessage.error(res.message || 'DOCX生成失败');
    }
  } catch (e: any) {
    console.error('DOCX报告生成失败:', e);
    ElMessage.error('DOCX报告生成失败: ' + (e.message || '网络错误'));
  } finally {
    generatingPDF.value = false;
  }
}

async function deleteReport(report: Record<string, any>) {
  try {
    await ElMessageBox.confirm('确定要删除此报告吗？', '确认删除', { type: 'warning' });
    const res = await legacyApi.delete(`/reports/${report.id}`);
    if (res && res.code === 0) {
      ElMessage.success('报告已删除');
      loadReports();
      loadReportStats();
    } else {
      ElMessage.error(res.message || '删除失败');
    }
  } catch (e: any) {
    if (e !== 'cancel') {
      console.error('删除报告失败:', e);
    }
  }
}

watch(activeTab, () => {
  loadReports();
});

onMounted(() => {
  loadReports();
  loadReportStats();
});
</script>

// frontend-react/src/pages/Reports.tsx
import { useCallback, useEffect, useState } from 'react';
import { reportsApi, situationalApi } from '@/api';
import type { ReportItem, ReportStats } from '@/api';
import Badge from '@/components/ui/badge';
import Button from '@/components/ui/button';
import { useToast } from '@/components/ui/use-toast';
import { useUserStore } from '@/stores/user';

const fieldCls =
  'rounded-md border border-cyan-500/20 bg-[#1a2340] px-3 py-2 text-sm text-gray-300 outline-none transition-colors placeholder:text-gray-500 focus:border-cyan-500/60';

type BadgeVariant = 'default' | 'success' | 'warning' | 'danger';

const TYPE_BADGE: Record<string, { label: string; variant: BadgeVariant }> = {
  djpp: { label: '等保测评', variant: 'danger' },
  virus: { label: '病毒查杀', variant: 'success' },
  baseline: { label: '基线检查', variant: 'warning' },
  scan: { label: '安全扫描', variant: 'default' },
  weekly: { label: '安全周报', variant: 'default' },
  monthly: { label: '安全月报', variant: 'default' },
  daily: { label: '安全日报', variant: 'default' },
  patrol: { label: '巡检报告', variant: 'default' }
};

const GEN_TYPES: Array<{ value: string; label: string }> = [
  { value: 'daily', label: '日报' },
  { value: 'weekly', label: '周报' },
  { value: 'monthly', label: '月报' },
  { value: 'patrol', label: '巡检' }
];

const CSV_TYPES: Array<{ value: string; label: string }> = [
  { value: 'alerts', label: '安全告警' },
  { value: 'scan', label: '扫描结果' },
  { value: 'baseline', label: '基线检查' },
  { value: 'reports', label: '报告列表' }
];

interface ReportRow extends ReportItem {
  hasDOCX: boolean;
}

/** 详情 content 可能是对象或字符串，统一转为纯文本展示（防 XSS） */
function contentToText(content: unknown): string {
  if (content == null) return '暂无内容';
  if (typeof content === 'string') return content || '暂无内容';
  if (typeof content === 'object') {
    const obj = content as Record<string, unknown>;
    if (typeof obj.content === 'string' && obj.content) return obj.content;
    return JSON.stringify(content, null, 2);
  }
  return String(content);
}

export default function Reports() {
  const { toast } = useToast();

  // 统计
  const [stats, setStats] = useState<ReportStats | null>(null);
  // 列表
  const [reports, setReports] = useState<ReportRow[]>([]);
  const [loading, setLoading] = useState(true);
  // 生成新报告
  const [genType, setGenType] = useState('weekly');
  const [generating, setGenerating] = useState(false);
  // 详情
  const [detail, setDetail] = useState<{ title: string; content: string } | null>(null);
  // 导出 CSV
  const [csvType, setCsvType] = useState('alerts');
  const [exportingCsv, setExportingCsv] = useState(false);
  // DOCX 生成中
  const [docxGeneratingId, setDocxGeneratingId] = useState<number | null>(null);

  const loadReports = useCallback(async () => {
    setLoading(true);
    try {
      const res = await reportsApi.list({ page: 1, pageSize: 100 });
      setReports((res.reports || []).map((r) => ({ ...r, hasDOCX: Boolean(r.hasDOCX) })));
    } catch {
      setReports([]);
    }
    setLoading(false);
  }, []);

  const loadStats = useCallback(async () => {
    try {
      const data = await reportsApi.stats();
      setStats(data || null);
    } catch {
      setStats(null);
    }
  }, []);

  useEffect(() => {
    loadReports();
    loadStats();
  }, [loadReports, loadStats]);

  /** 带鉴权头的流式下载（CSV/DOCX 均要求 Bearer token） */
  async function downloadWithAuth(url: string, fallbackName: string) {
    const token = useUserStore.getState().token;
    const resp = await fetch(url, { headers: { Authorization: `Bearer ${token}` } });
    if (!resp.ok) throw new Error('下载失败');
    const blob = await resp.blob();
    const disposition = resp.headers.get('Content-Disposition') || '';
    const match = disposition.match(/filename="?([^";]+)"?/);
    const filename = match ? match[1] : fallbackName;
    const objUrl = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = objUrl;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(objUrl);
  }

  /** 批量导出 CSV */
  async function exportCsv() {
    setExportingCsv(true);
    try {
      await reportsApi.exportCsv(csvType);
      const url = `/api/reports/export/csv?type=${csvType}`;
      await downloadWithAuth(url, `${csvType}_export_${new Date().toISOString().slice(0, 10)}.csv`);
      const label = CSV_TYPES.find((t) => t.value === csvType)?.label || csvType;
      toast({ title: `${label}数据已导出`, variant: 'success' });
    } catch {
      toast({ title: 'CSV 导出失败', variant: 'error' });
    }
    setExportingCsv(false);
  }

  /** 生成新报告（日报/周报/月报/巡检） */
  async function handleGenerate() {
    const opt = GEN_TYPES.find((t) => t.value === genType);
    const label = opt?.label || genType;
    setGenerating(true);
    try {
      await situationalApi.generateReport(genType, `${label} - ${new Date().toLocaleDateString('zh-CN')}`);
      toast({ title: `${label}已生成`, variant: 'success' });
      loadReports();
      loadStats();
    } catch {
      toast({ title: '报告生成失败', variant: 'error' });
    }
    setGenerating(false);
  }

  /** 查看详情 */
  async function viewReport(row: ReportRow) {
    try {
      const data = await reportsApi.detail(row.id);
      const content = contentToText((data as { content?: unknown }).content);
      setDetail({ title: row.title || '报告详情', content });
    } catch {
      setDetail({ title: row.title || '报告详情', content: '暂无内容' });
    }
  }

  /** 生成 DOCX 并下载（后端存在 /reports/download/:filename 真实路由） */
  async function generateDocx(row: ReportRow) {
    setDocxGeneratingId(row.id);
    toast({ title: '正在生成 DOCX 报告，请稍候...', variant: 'default' });
    try {
      const res = await reportsApi.generateDocx(row.id);
      if (res.downloadUrl) {
        await downloadWithAuth(res.downloadUrl, `report_${row.id}.docx`);
        toast({ title: 'DOCX 报告已下载', variant: 'success' });
        loadReports();
      } else {
        toast({ title: 'DOCX 生成失败', variant: 'error' });
      }
    } catch {
      toast({ title: 'DOCX 生成失败', variant: 'error' });
    }
    setDocxGeneratingId(null);
  }

  /** 删除报告 */
  async function deleteReport(row: ReportRow) {
    try {
      await reportsApi.remove(row.id);
      toast({ title: '报告已删除', variant: 'success' });
      loadReports();
      loadStats();
    } catch {
      toast({ title: '删除失败', variant: 'error' });
    }
  }

  const statCards: Array<{ label: string; value: number; color: string }> = [
    { label: '总报告数', value: stats?.total || 0, color: 'text-cyan-400' },
    { label: '等保测评报告', value: stats?.djpp || 0, color: 'text-red-400' },
    { label: '病毒查杀报告', value: stats?.virus || 0, color: 'text-green-400' },
    { label: '基线检查报告', value: stats?.baseline || 0, color: 'text-amber-400' }
  ];

  return (
    <div className="space-y-5">
      {/* 页头 */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-xl font-bold text-white">报告管理</h2>
          <p className="mt-1 text-sm text-gray-400">集中管理安全日报、周报、月报、巡检及各类专项报告</p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <div className="flex items-center gap-2">
            <select className={`${fieldCls} w-[130px]`} value={csvType} onChange={(e) => setCsvType(e.target.value)}>
              {CSV_TYPES.map((t) => (
                <option key={t.value} value={t.value}>
                  {t.label}
                </option>
              ))}
            </select>
            <Button size="sm" variant="outline" disabled={exportingCsv} onClick={exportCsv}>
              {exportingCsv ? '导出中...' : '批量导出 CSV'}
            </Button>
          </div>
          <Button
            size="sm"
            variant="outline"
            onClick={() => {
              loadReports();
              loadStats();
            }}
          >
            刷新
          </Button>
        </div>
      </div>

      {/* 统计卡 */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        {statCards.map((s) => (
          <div key={s.label} className="rounded-lg border border-cyan-500/20 bg-[#16213e]/80 p-4">
            <div className={`text-3xl font-bold ${s.color}`}>{s.value}</div>
            <div className="mt-1 text-sm text-gray-400">{s.label}</div>
          </div>
        ))}
      </div>

      {/* 生成新报告 */}
      <div className="rounded-lg border border-cyan-500/20 bg-[#16213e]/80 p-5">
        <div className="mb-4 text-sm font-semibold text-cyan-300">生成新报告</div>
        <div className="flex flex-wrap items-center gap-3">
          <select className={`${fieldCls} w-[140px]`} value={genType} onChange={(e) => setGenType(e.target.value)}>
            {GEN_TYPES.map((t) => (
              <option key={t.value} value={t.value}>
                {t.label}
              </option>
            ))}
          </select>
          <Button size="md" disabled={generating} onClick={handleGenerate}>
            {generating ? '生成中...' : '生成报告'}
          </Button>
        </div>
      </div>

      {/* 报告列表 */}
      <div className="rounded-lg border border-cyan-500/20 bg-[#16213e]/80 p-5">
        <div className="mb-4 text-sm font-semibold text-cyan-300">报告列表</div>
        <div className="w-full overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-cyan-500/20 text-left text-xs text-cyan-200/70">
                <th className="px-2 py-2 font-medium">ID</th>
                <th className="px-2 py-2 font-medium">报告标题</th>
                <th className="px-2 py-2 font-medium">类型</th>
                <th className="px-2 py-2 font-medium">生成者</th>
                <th className="px-2 py-2 font-medium">DOCX</th>
                <th className="px-2 py-2 font-medium">生成时间</th>
                <th className="px-2 py-2 font-medium">操作</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {reports.map((r) => {
                const badge = TYPE_BADGE[r.type] || { label: r.typeLabel || r.type, variant: 'default' as BadgeVariant };
                return (
                  <tr key={r.id} className="hover:bg-white/5">
                    <td className="px-2 py-2 text-gray-400">{r.id}</td>
                    <td className="max-w-[280px] truncate px-2 py-2 text-gray-300">{r.title}</td>
                    <td className="px-2 py-2">
                      <Badge variant={badge.variant}>{badge.label}</Badge>
                    </td>
                    <td className="px-2 py-2 text-gray-400">{r.generatedBy || '-'}</td>
                    <td className="px-2 py-2">
                      {r.hasDOCX ? (
                        <Badge variant="success">已生成</Badge>
                      ) : (
                        <span className="text-xs text-gray-500">未生成</span>
                      )}
                    </td>
                    <td className="px-2 py-2 text-gray-400">
                      {r.generatedAt ? new Date(r.generatedAt).toLocaleString('zh-CN') : '-'}
                    </td>
                    <td className="px-2 py-2">
                      <div className="flex gap-3">
                        <button
                          type="button"
                          onClick={() => viewReport(r)}
                          className="text-xs text-cyan-400 transition-colors hover:text-cyan-300"
                        >
                          查看
                        </button>
                        <button
                          type="button"
                          disabled={docxGeneratingId !== null}
                          onClick={() => generateDocx(r)}
                          className="text-xs text-amber-400 transition-colors hover:text-amber-300 disabled:opacity-50"
                        >
                          {docxGeneratingId === r.id ? '生成中...' : '生成 DOCX'}
                        </button>
                        <button
                          type="button"
                          onClick={() => deleteReport(r)}
                          className="text-xs text-red-400 transition-colors hover:text-red-300"
                        >
                          删除
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
              {!loading && reports.length === 0 && (
                <tr>
                  <td colSpan={7} className="px-2 py-6 text-center text-gray-500">
                    暂无报告
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* 报告详情弹窗 */}
      {detail && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-black/60" onClick={() => setDetail(null)} />
          <div className="relative z-10 flex max-h-[85vh] w-full max-w-4xl flex-col rounded-lg border border-cyan-500/20 bg-[#0f1a33] shadow-xl">
            <div className="flex items-center justify-between border-b border-white/5 px-5 py-4">
              <h3 className="text-base font-semibold text-white">{detail.title}</h3>
              <button
                type="button"
                onClick={() => setDetail(null)}
                className="text-xl leading-none text-gray-400 hover:text-gray-200"
                aria-label="关闭"
              >
                ×
              </button>
            </div>
            <div className="flex-1 overflow-y-auto px-5 py-4">
              <pre className="whitespace-pre-wrap text-sm leading-relaxed text-gray-200">{detail.content}</pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
